### ISSUE TITLE
sparklyr remote connect : spark_connect() 

### ISSUE THREAD

**Issue by IrishBird** [rstudio/sparklyr#299] opened 2016-10-31 09:56 UTC
I try to use sparklyr to connect to a remote spark server:
I wrote it as : 
for example : the clusterlp is: 139.133.566.90“ and port is : 10001
soI wrote as: 
sc <- spark_connect(master = "spark://139.133.566.90:10001",spark_home = "/opt/spark/spark-1.6.2-bin-hadoop2.6",version="1.6.2")
when I run it then the error is shown as blow :  I have googled a a lot: here is one thread : http://stackoverflow.com/questions/39798798/connect-sparklyr-to-remote-spark-connection
which probably met the issue as mine, however no answer yet.

Error: Failed during initialize_connection() java.lang.NullPointerException
	at org.apache.spark.SparkContext.<init>(SparkContext.scala:583)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sparklyr.Handler.handleMethodCall(handler.scala:139)
	at sparklyr.Handler.channelRead0(handler.scala:63)
	at sparklyr.Handler.channelRead0(handler.scala:15)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec

**Comment by javierluraschi** [comment] 2016-11-01 17:40
@IrishBird are you using the RStudio desktop to connect? If that's the case, this is currently unsupported and instead, the recommended approach is to install RStudio Server in the Spark cluster. We are exploring alternatives to this through Livy, is Livy a service already installed in your cluster or that would be feasible to install?

**Comment by IrishBird** [comment] 2016-11-02 03:05
Thank you your for suggestion . And .I got it now.Yes. I am using  RStudio desktop to connect.
so this Rstudio sever should be in one of the node of Spark.. then I don't fee it is remote connect...
And when you said install Livy: does it means that If I install LIvy in cluster, then I could use RStudio desktop  ? For some reason,I don't want to touch the cluster env....

**Comment by IrishBird** [comment] 2016-11-02 04:38
@javierluraschi  
Before this,I haven't used R studio server before, and Let me explore Rstudio server in the first place. and then get back to this.
Thanks for your clue.

**Comment by edgararuiz** [comment] 2016-11-02 14:00
@IrishBird -  Is your cluster inside your network or in the cloud?

**Comment by IrishBird** [comment] 2016-11-03 02:11
@edgararuiz  the cluster inside my network.

**Comment by edgararuiz** [comment] 2016-11-03 02:49
Cool, and to double check, the master setting you have matches to what's on the Spark UI (normally port 8080 on the master)

![spark_arrow](https://cloud.githubusercontent.com/assets/7875923/19954375/c7caef9a-a145-11e6-9b2f-0bc1bb9924f2.jpg)

**Comment by IrishBird** [comment] 2016-11-04 07:00
@edgararuiz  I was trying to use this IP :port to access. but it was used on Rstudio Desktop. I was ignorant. and now I install Rstudo Server on the server where also install Spark. but it seems that I can't open the WEB of RStudio Server, because the server is built on Ali cloud service.and i need to solve the issue of PORT :8787 . (I don't have admin privileg :( to open this port )

**Comment by joebling** [comment] 2017-04-18 05:50
@edgararuiz  Can I use sparklyr connect to spark from a client?
It seems it doesn't work from rstudio web.

But when use R in this client, it seems work?

![image](https://cloud.githubusercontent.com/assets/18331158/25116173/9f551e70-243d-11e7-8a82-a712d5cd56bd.png)


thanks

**Comment by kevinykuo** [comment] 2017-04-18 21:44
@joebling what error message are you getting when trying to connect from RStudio Server?

**Comment by joebling** [comment] 2017-04-19 01:09
@kevinykuo 


> sc <- spark_connect(master = "yarn-client", spark_home = '/appcom/service/spark')
Error in force(code) :
  Failed during initialize_connection: java.net.ConnectException: Call From twin-sz01-nbd-prd-10013.16qian.cn/10.8.34.63 to 0.0.0.0:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
    at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
    at org.apache.hadoop.ipc.Client.call(Client.java:1473)
    at org.apache.hadoop.ipc.Client.call(Client.java:1400)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
    at com.sun.proxy.$Proxy10.getClusterMetrics(Unknown Source)
    at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getClusterMetrics(ApplicationClientProtocolPBClientImpl.java:202)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy11.getClusterMetrics(Unknown Source)
    at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getYarnClusterMetrics(YarnClientImpl.java:461)
    at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:154)
    at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:154)
    at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
    at org.apache.spark.deploy.yarn.Client.logInfo(Client.scala:60)
    at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:153)
    at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:56)
    at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:149)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:497)
    at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2258)
    at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sparklyr.Invoke$.invoke(invoke.scala:94)
    at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
    at sparklyr.StreamHandler$.read(stream.scala:55)
    at sparklyr.BackendHandler.channelRead0(handler.scala:49)
    at sparklyr.BackendHandler.channelRead0(handler.scala:14)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
    at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:608)
    at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:706)
    at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:369)
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1522)
    at org.apache.hadoop.ipc.Client.call(Client.java:1439)
    ... 48 more



---- Output Log ----
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sparklyr.Invoke$.invoke(invoke.scala:94)
    at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
    at sparklyr.StreamHandler$.read(stream.scala:55)
    at sparklyr.BackendHandler.channelRead0(handler.scala:49)
    at sparklyr.BackendHandler.channelRead0(handler.scala:14)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.hadoop.net.SocketIOWithTimeout.connect(Sock

**Comment by joebling** [comment] 2017-04-19 01:09
> sc <- spark_connect(master = "yarn-client", spark_home = '/appcom/service/spark')
Error in force(code) :
  Failed during initialize_connection: java.net.ConnectException: Call From twin-sz01-nbd-prd-10013.16qian.cn/10.8.34.63 to 0.0.0.0:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
    at sun.reflect.GeneratedConstructorAccessor7.newInstance(Unknown Source)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
    at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:791)
    at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:731)
    at org.apache.hadoop.ipc.Client.call(Client.java:1473)
    at org.apache.hadoop.ipc.Client.call(Client.java:1400)
    at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:232)
    at com.sun.proxy.$Proxy10.getClusterMetrics(Unknown Source)
    at org.apache.hadoop.yarn.api.impl.pb.client.ApplicationClientProtocolPBClientImpl.getClusterMetrics(ApplicationClientProtocolPBClientImpl.java:202)
    at sun.reflect.GeneratedMethodAccessor1.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:187)
    at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
    at com.sun.proxy.$Proxy11.getClusterMetrics(Unknown Source)
    at org.apache.hadoop.yarn.client.api.impl.YarnClientImpl.getYarnClusterMetrics(YarnClientImpl.java:461)
    at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:154)
    at org.apache.spark.deploy.yarn.Client$$anonfun$submitApplication$1.apply(Client.scala:154)
    at org.apache.spark.internal.Logging$class.logInfo(Logging.scala:54)
    at org.apache.spark.deploy.yarn.Client.logInfo(Client.scala:60)
    at org.apache.spark.deploy.yarn.Client.submitApplication(Client.scala:153)
    at org.apache.spark.scheduler.cluster.YarnClientSchedulerBackend.start(YarnClientSchedulerBackend.scala:56)
    at org.apache.spark.scheduler.TaskSchedulerImpl.start(TaskSchedulerImpl.scala:149)
    at org.apache.spark.SparkContext.<init>(SparkContext.scala:497)
    at org.apache.spark.SparkContext$.getOrCreate(SparkContext.scala:2258)
    at org.apache.spark.SparkContext.getOrCreate(SparkContext.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sparklyr.Invoke$.invoke(invoke.scala:94)
    at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
    at sparklyr.StreamHandler$.read(stream.scala:55)
    at sparklyr.BackendHandler.channelRead0(handler.scala:49)
    at sparklyr.BackendHandler.channelRead0(handler.scala:14)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.hadoop.net.SocketIOWithTimeout.connect(SocketIOWithTimeout.java:206)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:530)
    at org.apache.hadoop.net.NetUtils.connect(NetUtils.java:494)
    at org.apache.hadoop.ipc.Client$Connection.setupConnection(Client.java:608)
    at org.apache.hadoop.ipc.Client$Connection.setupIOstreams(Client.java:706)
    at org.apache.hadoop.ipc.Client$Connection.access$2800(Client.java:369)
    at org.apache.hadoop.ipc.Client.getConnection(Client.java:1522)
    at org.apache.hadoop.ipc.Client.call(Client.java:1439)
    ... 48 more



---- Output Log ----
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at sparklyr.Invoke$.invoke(invoke.scala:94)
    at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
    at sparklyr.StreamHandler$.read(stream.scala:55)
    at sparklyr.BackendHandler.channelRead0(handler.scala:49)
    at sparklyr.BackendHandler.channelRead0(handler.scala:14)
    at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
    at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
    at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
    at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:137)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
    at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
    at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
    at org.apache.hadoop.net.SocketIOWithTimeout.connect(Sock

**Comment by edgararuiz** [comment] 2017-04-19 01:25
@joebling, can you try set or confirm if the JAVA_HOME is set?

**Comment by joebling** [comment] 2017-04-19 01:37
@edgararuiz 

From rstudio web,it seems that R cann't get JAVA_HOME 

![Uploading 微信截图_20170419093017.png…]()

that might be the problem. 

ps: I install Rstudio server on a hadoop client.

**Comment by joebling** [comment] 2017-04-19 01:38
@edgararuiz 
From rstudio web,it seems that R cann't get JAVA_HOME. 

> Sys.getenv()
DISPLAY                                     :0
EDITOR                                      vi
GIT_ASKPASS                                 rpostback-askpass
HOME                                        /home/qiuliangliang
LANG                                        en_US.UTF-8
LD_LIBRARY_PATH                             /usr/lib64/R/lib::/lib:/usr/lib/jvm/jre/lib/amd64/server:/usr/lib/jvm/jre/lib/amd64:/usr/lib/jvm/java/lib/amd64:/usr/java/packages/lib/amd64:/lib:/usr/lib:@JAVA_LD@
LN_S                                        ln -s
LOGNAME                                     qiuliangliang
MAKE                                        make
NLSPATH                                     /usr/dt/lib/nls/msg/%L/%N.cat
PAGER                                       /usr/bin/less
PATH                                        /usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
R_BROWSER                                   /usr/bin/xdg-open
R_BZIPCMD                                   /usr/bin/bzip2
R_DOC_DIR                                   /usr/share/doc/R-3.3.1
R_GZIPCMD                                   /usr/bin/gzip
R_HOME                                      /usr/lib64/R
R_INCLUDE_DIR                               /usr/include/R
R_LIBS_SITE                                 /usr/local/lib/R/site-library:/usr/local/lib/R/library:/usr/lib64/R/library:/usr/share/R/library
R_LIBS_USER                                 ~/R/x86_64-redhat-linux-gnu-library/3.3
R_PAPERSIZE                                 a4
R_PDFVIEWER                                 /usr/bin/xdg-open
R_PLATFORM                                  x86_64-redhat-linux-gnu
R_PRINTCMD                                  lpr
R_RD4PDF                                    times,hyper
R_SESSION_TMPDIR                            /tmp/Rtmp8seL7n
R_SHARE_DIR                                 /usr/share/R
R_SYSTEM_ABI                                linux,gcc,gxx,gfortran,?
R_TEXI2DVICMD                               /usr/bin/texi2dvi
R_UNZIPCMD                                  /usr/bin/unzip
R_ZIPCMD                                    
RMARKDOWN_MATHJAX_PATH                      /usr/lib/rstudio-server/resources/mathjax-26
RS_RPOSTBACK_PATH                           /usr/lib/rstudio-server/bin/rpostback
RSTUDIO                                     1
RSTUDIO_HTTP_REFERER                        http://10.8.34.63:8787/
RSTUDIO_PANDOC                              /usr/lib/rstudio-server/bin/pandoc
RSTUDIO_SESSION_STREAM                      qiuliangliang-d
RSTUDIO_USER_IDENTITY                       qiuliangliang
RSTUDIO_WINUTILS                            bin/winutils
SED                                         /bin/sed
SSH_ASKPASS                                 rpostback-askpass
TAR                                         /bin/gtar
USER                                        qiuliangliang
that might be the problem.

ps: I install Rstudio server on a hadoop client.

**Comment by edgararuiz** [comment] 2017-04-19 01:39
Try this inside R: Sys.getenv("JAVA_HOME")

**Comment by joebling** [comment] 2017-04-19 01:40
@kevinykuo 

> Sys.getenv("JAVA_HOME")
[1] ""

**Comment by joebling** [comment] 2017-04-19 01:41
@edgararuiz 

When use R in the shell on the same client, it get 
> Sys.getenv("JAVA_HOME")
[1] "/usr/lib/jvm/java"

**Comment by edgararuiz** [comment] 2017-04-19 01:44
ok, let's try this in RStudio:

```
Sys.setenv(JAVA_HOME = "/usr/lib/jvm/java")

```

**Comment by edgararuiz** [comment] 2017-04-19 02:09
oh! is this a Hadoop Cluster or a Spark Stand Alone cluster?

**Comment by joebling** [comment] 2017-04-19 02:21
@edgararuiz 

a hadoop client.

**Comment by edgararuiz** [comment] 2017-04-20 12:52
Ok, what kind of security does the Hadoop cluster have?

**Comment by peddollakishore** [comment] 2017-06-06 07:56
Hi edgaruiz

i am connected to spark standalone cluster but when i am importing data from cassandra its keep on waiting stage please help on this

**Comment by peddollakishore** [comment] 2017-06-07 06:00
Hi All
Any solution for above problem.....
Please updates if any.

**Comment by edgararuiz** [comment] 2017-06-07 16:00
Hi @peddollakishore , have you considered using the sparklyr extension for this: https://github.com/AkhilNairAmey/crassy

**Comment by peddollakishore** [comment] 2017-06-08 06:39
Hi @edgararuiz , when i try to load **library(crassy)** package it through bellow error, 
`> install.packages("crassy")
Installing package into ‘/home/rstudio/R/x86_64-pc-linux-gnu-library/3.4’
(as ‘lib’ is unspecified)
Warning in install.packages :
  package ‘crassy’ is not available (for R version 3.4.0)`

**Comment by peddollakishore** [comment] 2017-06-08 06:50
@edgararuiz i installed **carassy** package using Github, now i am going farther steps

**Comment by peddollakishore** [comment] 2017-06-08 07:14
Hi @edgararuiz while i am try to load cassandra table bellow is the error,
`> library(sparklyr)
> library(dplyr)
> library(crassy)
> sc <- spark_connect(master = "spark://XXXXXXXXX:7077")
> spk_handle = crassy::spark_load_cassandra_table(session = sc,cass_keyspace = "test", cass_tbl = "kv", 
+   spk_tbl_name  = "spk_tbl")
Error in crassy::spark_load_cassandra_table(session = sc, cass_keyspace = "test",  : 
  unused argument (session = sc)`

**Comment by edgararuiz** [comment] 2017-06-08 15:29
Cool, let me know if it ends up working for you

**Comment by peddollakishore** [comment] 2017-06-09 10:59
Hi @edgararuiz while using crassy package it is also same issue waiting waiting....here is the code 
`library(sparklyr)
library(dplyr)
library(crassy)
Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
sc <- spark_connect(master = "local")
sc <- spark_connect(master = "spark://XXX.XXX.XXX:7077")
spark_load_cassandra_table(sc, "test", "kv", "spkr_tbl_name", partition_filter = FALSE, select_cols = FALSE, cache_table = FALSE)
**Waiting......**
`

**Comment by peddollakishore** [comment] 2017-06-09 11:05
This code for local spark cluster it is executed successfully bellow is the code. 
`>library(sparklyr)
>library(dplyr)
>library(crassy)
>Sys.setenv(SPARK_HOME='/home/ubuntu/spark')
>sc <- spark_connect(master = "local")
> spark_load_cassandra_table(sc, "test", "kv", "spkr_tbl_name", partition_filter = FALSE, select_cols = FALSE, cache_table = FALSE)
Source:   query [3 x 2]
Database: spark connection master=local[2] app=sparklyr local=TRUE

# A tibble: 3 x 2
    key value
  <chr> <int>
1  key1     1
2  key3     3
3  key2     2`

**Comment by edgararuiz** [comment] 2017-06-09 18:08
How many nodes are there in your cluster?

**Comment by peddollakishore** [comment] 2017-06-10 16:57
Hi @edgararuiz [https://ibb.co/ncun0v](url)

**Comment by peddollakishore** [comment] 2017-06-10 17:26
https://ibb.co/ncun0v

**Comment by edgararuiz** [comment] 2017-06-10 19:09
Ok, I'm trying to figure out if your session is receiving resources.  Can you please start a new session and share with me an updated screenshot?

**Comment by peddollakishore** [comment] 2017-06-12 07:08
Hi @edgararuiz please find the spark cluster new session screen shots and R-server code image 
![2017-06-12 12_20_40-spark master at spark___ip-172-31-1-101 ec2 internal_7077](https://user-images.githubusercontent.com/16456445/27022446-9bf45594-4f6b-11e7-95f6-b5eebc285984.png)

**Comment by peddollakishore** [comment] 2017-06-13 06:00
Hi @edgararuiz any solution for that, if any update on that issue please let me know.

**Comment by edgararuiz** [comment] 2017-06-13 13:03
Hi @peddollakishore , the only thing I can think of is to open an issue in crassy

**Comment by peddollakishore** [comment] 2017-06-14 10:30
Hi @edgararuiz we found below error for that, if you know any thing about this error please let me know,

`WARN TaskSchedulerImpl: Initial job has not accepted any resources; check your cluster UI to ensure that workers are registered and have sufficient resources`

**Comment by statmatt** [comment] 2017-07-18 17:32
+1 on this issue, specifically that sparklyr needs to support yarn-cluster mode connections. Maintaining that one must install Rstudio-Server on the cluster master to then use sparklyr is a needless constraint. If I have an EMR cluster up that I want to submit jobs to from my Rstudio Desktop instance, this should be possible ... I can submit it via any other spark tool with the correct core-site.xml and yarn-site.xml, so sparklyr needs to implement this for feature parity.

**Comment by javierluraschi** [comment] 2017-08-17 21:39
Basic support for `yarn-cluster` was added on `0.6`; however, this has a few caveats:

- Does not currently support high-availability
- Assumes application runs in the resource manager and there is a single one
- Best used in combinarion with `config$sparklyr.gateway.address` to point `saprklyr` to the yarn master. 

Updates to `yarn-cluster` in the works here: https://github.com/rstudio/sparklyr/pull/905, closing this issue, but follow up on that PR for `yarn-cluster` related features and issues.

**Closed by javierluraschi** 2017-08-17 21:39 UTC
Labels: connection

**Comment by kruny1001** [comment] 2017-09-10 01:21
Hi, @peddollakishore 

I had a similar issue like yours. Can you check the slave's information from spark ui at 4040 port. From Environment tab, your slave node may look at your client(local) setting. That is why it keeps freeze I guess.

**Comment by peddollakishore** [comment] 2017-09-18 12:14
Hi @kruny1001 @javierluraschi @statmatt thanks for reply.

i have one doubt , i need to install spark, scala, java and R-server in slave nodes also

**Comment by javierluraschi** [comment] 2017-09-18 18:43
@peddollakishore 

For `yarn-client`:
1 Driver Node: Install R, RStudio (if desired). Java, scala and spark should already be installed in this node for correct Spark configurations.
2. WOrker Nodes: Install R, if you wish to use `spark_apply()`.
