### ISSUE TITLE
Accuracy metric failing for Spark 1.6.0

### ISSUE THREAD

**Issue by nwstephens** [rstudio/sparklyr#355] opened 2016-12-01 16:50 UTC
The `accuracy` metric in `ml_classification_eval` fails for Spark 1.6.0 but works for Spark 2.0.0. The accuracy metric does appear to be supported in Spark 1.6.0 see [here](https://spark.apache.org/docs/1.6.0/mllib-evaluation-metrics.html). Note that other metrics appear unaffected, like `f1`, which works for both versions of Spark. Example below.

```
library(sparklyr)
library(dplyr)

sc <- spark_connect(master = "local", version = "1.6.0") # works for 2.0.0
titanic <- data.frame(Titanic, stringsAsFactors = FALSE)
titanic_tbl <- copy_to(sc, titanic, overwrite = TRUE)
ml_fit <- ml_logistic_regression(titanic_tbl, Survived ~ .)
ml_pred <- sdf_predict(ml_fit, titanic_tbl)
ml_pred <- mutate(ml_pred, actual = ifelse(Survived == "No", 1L, 0L))
ml_classification_eval(ml_pred, "actual", "prediction", "accuracy") # works for "f1"

Error: java.lang.IllegalArgumentException: mcEval_79c684d5ddb1 parameter metricName given invalid value accuracy.
    at org.apache.spark.ml.param.Param.validate(params.scala:76)
    at org.apache.spark.ml.param.ParamPair.<init>(params.scala:509)
    at org.apache.spark.ml.param.Param.$minus$greater(params.scala:85)
    at org.apache.spark.ml.param.Params$class.set(params.scala:604)
    at org.apache.spark.ml.evaluation.Evaluator.set(Evaluator.scala:30)
    at org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator.setMetricName(MulticlassClassificationEvaluator.scala:59)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at sparklyr.Handler.handleMethodCall(handler.scala:118)
    at sparklyr.Handler.channelRead0(handler.scala:63)
    at sparklyr.Handler.channelRea
```

**Comment by slopp** [comment] 2016-12-01 21:47
@javierluraschi The issue is some metrics are support in 2.0.0 that are not supported in 1.6. 

For Multiclass Evaluators:
1.6 - supports "f1" (default), "precision", "recall", "weightedPrecision", "weightedRecall"
2.0 - supports "f1" (default), "weightedPrecision", "weightedRecall", "accuracy"

For Binary Classification Evaluator:
1.6 - "areaUnderROC" (default), "areaUnderPR"
2.0 -  areaUnderROC

https://spark.apache.org/docs/**1.6.0**/api/scala/index.html#org.apache.spark.ml.evaluation.MulticlassClassificationEvaluator  (replace with 2.0.0 to see the change)

https://spark.apache.org/docs/**2.0.0**/api/scala/index.html#org.apache.spark.ml.evaluation.BinaryClassificationEvaluator

We could add a check in R ... but that would mean updating that check for every version :/ I'm not sure what approach we've taken with the other ml functions. In this case, I'd argue that the error message is pretty clear, but I also agree that it is hard to find what options are supported.

Side note: I didn't implement the regression evaluator, but that would be a nice-to-have that would round out these functions.

**Comment by javierluraschi** [comment] 2017-05-10 06:14
I believe the change we want here is to improve error messages to be more descriptive as to what is supported in which versions.

**Comment by javierluraschi** [comment] 2017-08-17 23:16
Fixed with https://github.com/rstudio/sparklyr/pull/950

**Closed by javierluraschi** 2017-08-17 23:16 UTC
Labels: ml
