### ISSUE TITLE
Error connecting to Spark Instance 

### ISSUE THREAD

**Issue by ArunLakhotia** [rstudio/sparklyr#668] opened 2017-05-08 10:09 UTC
I am getting the following error on trying to connect to Spark Instance 
Error in spark_connect() : could not find function "spark_connect".

I had successfully installed sparlyr, dplyr and h2o. The spark instance is already running on the machine. I am able to view help when I execute the command ?spark_connect.

Using Sparkling water version - 2.1.2 
Spark version : 2.1.0
H20 :3.10.4.6

**Comment by javierluraschi** [comment] 2017-05-09 04:18
@ArunLakhotia have you run `library(sparklyr)` before `spark_connect(master ="local")`?

You can view help with `?spark_connect`.

**Comment by javierluraschi** [comment] 2017-09-13 23:01
This issue is most likely caused by missing to run `library(sparklyr)` before `spark_connect()`, closing.

**Closed by javierluraschi** 2017-09-13 23:01 UTC
Labels: h2o
