### ISSUE TITLE
Date values are shifted by one day

### ISSUE THREAD

**Issue by andreysharapov** [rstudio/sparklyr#1588] opened 2018-07-09 12:15 UTC
---

Hi

I am running spark 2.3.0.2.6.5.0 from Hortonworks
I have update the version of sparklyr from 0.6.2 to 0.8.4 and started experiencing very strange behavior when querying data from Hive that has columns with date type.
 
My query looks like this 

SELECT dat_formdate, sum(abverkauf) FROM qa01ch_data.PVT_SALES_AGG WHERE client_id = 4 AND dat_formdate >= '2018-03-26' AND dat_formdate <='2018-04-23' GROUP BY dat_formdate  ORDER BY dat_formdate

When I query Hive directly (using beeline)  I get 

+---------------+---------------------+--+
| dat_formdate  |         _c1         |
+---------------+---------------------+--+
| 2018-03-26    | 11111111                     |
| 2018-03-27    | 22222222                    |

.....................................................................................

| 2018-04-22    | 33333333                         |
| 2018-04-23    | 44444444                     |
+---------------+---------------------+--+

Notice the dates go from 2018-03-26 to  2018-04-23

Now, I run the same query with sparklyr like this 

result <- hive %>% invoke("sql", query) %>% collect()
and I get

 2018-03-25   11111111
 2018-03-26   22222222
............................................................
 2018-04-21      33333333
 2018-04-22      44444444 

You can see that dates do not satisfy the query constraints and are shifted by one day

Why is that?

```r
spark_version <- "2.3.0"
sc <- spark_connect(master = "local", version = spark_version)

# your reproducible example here
```

**Comment by andreysharapov** [comment] 2018-07-09 12:42
PySpark give correct dates. On the same Hortonworks platform.

**Comment by javierluraschi** [comment] 2018-07-09 23:42
@andreysharapov I believe this is a duplicate of https://github.com/rstudio/sparklyr/issues/1561, please upgrade using:

```
devtools::install_github("rstudio/sparklyr")
```

Just marked the fix to be back-ported in a patch release.

**Comment by javierluraschi** [comment] 2018-09-12 16:50
Looks fixed, closing.

**Closed by javierluraschi** 2018-09-12 16:50 UTC
Labels: serialization
