### ISSUE TITLE
Unable to load Cassandra table using a spark session and R

### ISSUE THREAD

**Issue by prbhadra** [rstudio/sparklyr#520] opened 2017-02-26 02:48 UTC
Hi ,
I am using Spark 2.1.0 and trying to connect a Cassandra cluster. I have used the latest sparklyr. I have set the default configurations as below 👍 
default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  spark.sql.shuffle.partitions.local: !expr parallel::detectCores()

  # cassandra settings
spark.cassandra.connection.host:<Cassandra IP>
spark.cassandra.auth.username: <uid>
spark.cassandra.auth.password:<pass>

sparklyr.defaultPackages:
- com.databricks:spark-csv_2.11:1.5.0
- com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-RC1
- com.datastax.cassandra:cassandra-driver-core:3.1.4

I have performed the following actions. Everything went fine until I tried to invoke the read function. /i have set the jar location explicitly.

> library(sparklyr)
> config <- spark_config()
Warning message:
In readLines(input, encoding = "UTF-8") :
  incomplete final line found on '/home/bsc/BSCAnalytics/config.yml'
> config[["sparklyr.jars.default"]] <- c("/home/bsc/BSCAnalytics/cassandra-driver-core-3.1.4.jar")
> 
> sc <- spark_connect(master = "local", version = "2.1.0")
Warning message:
In readLines(input, encoding = "UTF-8") :
  incomplete final line found on '/home/bsc/BSCAnalytics/config.yml'
> Spark.session <- sparklyr::invoke_static(sc, "org.apache.spark.sql.SparkSession", "builder") %>% sparklyr::invoke("config", "spark.cassandra.connection.host", "<Cassandra IP>") %>% sparklyr::invoke("getOrCreate")

when I try to invoke the read function, I witness the following error:
> event_df <- invoke(Spark.session, "read") %>% invoke("format", "org.apache.spark.sql.cassandra") %>% invoke("option", "keyspace", "kps") %>% invoke("option", "table", "tab_event") %>% invoke("load")
Error: java.lang.ClassNotFoundException: Failed to find data source: org.apache.spark.sql.cassandra. Please find packages at http://spark.apache.org/third-party-projects.html
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:569)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass$lzycompute(DataSource.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.providingClass(DataSource.scala:86)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:325)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:152)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:125)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:94)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:89)
	at sparklyr.StreamHandler$.read(stream.scala:55)
	at sparklyr.BackendHandler.channelRead0(handler.scala:49)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:346)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:367)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:353)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:652)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:575)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:489)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:451)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.cassandra.DefaultSource
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25$$anonfun$apply$13.apply(DataSource.scala:554)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25$$anonfun$apply$13.apply(DataSource.scala:554)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25.apply(DataSource.scala:554)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$25.apply(DataSource.scala:554)
	at scala.util.Try.orElse(Try.scala:84)
	at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:554)
	... 39 more

**Comment by javierluraschi** [comment] 2017-02-28 23:53
@prbhadra This worked for me:

Install Cassandra, I followed (https://www.datastax.com/2012/01/working-with-apache-cassandra-on-mac-os-x):

```
curl -OL http://downloads.datastax.com/community/dsc.tar.gz
tar -xzf dsc.tar.gz 
cd dsc-cassandra-3.0.9/bin
./cassandra
```

Created some tables:

```
cd dsc-cassandra-3.0.9/bin
./cqlsh
create keyspace dev with replication = {'class':'SimpleStrategy','replication_factor':1};
use dev;
create table emp (empid int primary key, emp_first varchar, emp_last varchar, emp_dept varchar);
insert into emp (empid, emp_first, emp_last, emp_dept) values (1,'fred','smith','eng');
```

Now, from sparklyr:

```{r}
library(sparklyr)

config <- spark_config()
config[["sparklyr.defaultPackages"]] <- c(
   "datastax:spark-cassandra-connector:2.0.0-RC1-s_2.11")

sc <- spark_connect(master = "local", version = "1.6.1", config = config)

df <- sparklyr:::spark_data_read_generic(
  sc,
  "org.apache.spark.sql.cassandra",
  "format", list(
    keyspace = "dev",
    table = "emp"
)) %>% invoke("load")

cassandra_tbl <- sparklyr:::spark_partition_register_df(
  sc,
  df,
  name = "emp",
  repartition = 0,
  memory = FALSE)
```

Then, `cassandra_tbl` can be use as any other table with `ml` functions, `dplyr`, `DBI`, etc.

```
cassandra_tbl
Source:   query [1 x 4]
Database: spark connection master=local[8] app=sparklyr local=TRUE

  empid emp_dept emp_first emp_last
  <int>    <chr>     <chr>    <chr>
1     1      eng      fred    smith
```

Make sure to match the Cassandra connection version with the Spark version, the full list is available here: https://spark-packages.org/package/datastax/spark-cassandra-connector

Notice that [spark_data_read_generic]( https://github.com/rstudio/sparklyr/blob/ecba68f1c663253c1c83fdd5f2cbcad41158879c/R/data_interface.R#L306-L314) is a private function since it makes use of `invoke`, would be great to create a CRAN extension that wraps this functionality and makes it available to others, [sparkhello](https://github.com/javierluraschi/sparkhello) is a simple extension to `sparklyr` to get started.

**Comment by renegademonkey** [comment] 2017-03-02 12:13
Hi @javierluraschi: thanks for this - I have also been having issues connecting to a cassandra database on a local cluster, this really cleared things up.

Can I just ask a related question: when bringing in databases from a certain Cassandra `keyspace` and `table`, can you at the same time filter the dataset, i.e. to only bring in some columns (i.e. using SQL-like `SELECT` commands)? I have a huge dataset which is causing memory overruns and would like to reduce it before bringing it into Spark. 

I've tried adding:

```
%>% invoke("option", "select", "id")
```

before `%>% invoke("load")`, but am just not sure of the exact syntax and placement of such a command in this process.

Apologies if this is slightly off-topic.

**Comment by prbhadra** [comment] 2017-03-02 19:11
Hi Javier,
Thank for sharing a detailed response. I would like to share following details for your perusal and seek your recommendations:

Our Spark(2.1) Clusters are not co located with Cassandra(3.x) nodes
Cassandra is secured with user ID and Password
I assume the connector jar can connect the version of Spark and Cassandra I am using

Please let me know the following:
1. Where do I place the Spark Cassandra connector jar and, how would Sparlyr refer to it? It seems you are passing the maven attributes to the function setting up the config parameter
2. Where do we pass the cluster IPs, user Id and Password?
3. How do we load frozen or any other Cassandra complex objects in a DF for further analysis?

**Comment by AkhilNairAmey** [comment] 2017-03-12 16:31
To answer 1) and 2) you can provide these in a `config.yml` which you pass to `spark_connect` (or have in your working directory when the connection is made).

```
default:
  spark.cassandra.connection.host:    cassandra
  ...

  # default spark packages to load
  sparklyr.defaultPackages:
    - com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3
```

**Comment by javierluraschi** [comment] 2017-05-10 07:40
I don't have a concrete recommendation yet, but I'll take a closer look before releasing `sparklyr 0.6`. In general, I would search online what the recommendations for using the Cassandra connector for Spark.

**Comment by sdanielzafar** [comment] 2017-06-19 00:35
I'm having a similar issue. I can load Cassandra tables when using the sparklyr-installed Spark. But having some major issues when trying to get data with an existing cluster that's already running. I've tried everything! On Cassandra 3, most recent sparklyr, and Spark 2.0.1.

```
sc <- spark_connect(master = "spark://MYSERVER.ADD.local:7077", 
                    spark_home = "/var/lib/Spark", 
                    version = "2.0.1", 
                    hadoop_version = "2.7")

parts = spark_load_cassandra_table(
  sc = sc,
  cass_keyspace = "test", 
  cass_tbl = "parts", 
  spk_tbl_name = "parts"
  )

```
with associated `config.yml`
```
default:
  # local-only configuration
  sparklyr.cores.local: !expr parallel::detectCores()
  spark.sql.shuffle.partitions.local: !expr parallel::detectCores()
  # spark.cassandra.connection.host: 127.0.0.1
  # spark.cassandra.auth.username: dzafar
  # spark.cassandra.auth.password: 
  
  # include the embedded csv package for spark 1.x
  sparklyr.csv.embedded: "^1.*"

  # default spark packages to load
  #sparklyr.defaultPackages: 
    - com.datastax.spark:spark-cassandra-connector_2.11:2.0.0-M3
    # - com.datastax.spark:spark-cassandra-connector_2.11:2.0.2
    # - com.datastax.cassandra:cassandra-driver-core:3.0.7
  

  # command line arguments to spark-shell
  # sparklyr.shell.*
  sparklyr.shell.driver-class-path: 
    - !expr Sys.getenv("SPARK_DRIVER_CLASSPATH")
```
Here is the error:
```
> parts
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 5 in stage 1.0 failed 4 times, most recent failure: Lost task 5.3 in stage 1.0 (TID 19, 10.96.26.48): java.io.IOException: Failed to open native connection to Cassandra at {127.0.0.1, 127.0.0.2, 127.0.0.3}:9042
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:163)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$3.apply(CassandraConnector.scala:149)
	at com.datastax.spark.connector.cql.CassandraConnector$$anonfun$3.apply(CassandraConnector.scala:149)
	at com.datastax.spark.connector.cql.RefCountedCache.createNewValueAndKeys(RefCountedCache.scala:31)
	at com.datastax.spark.connector.cql.RefCountedCache.acquire(RefCountedCache.scala:56)
	at com.datastax.spark.connector.cql.CassandraConnector.openSession(CassandraConnector.scala:82)
	at com.datastax.spark.connector.rdd.CassandraTableScanRDD.compute(CassandraTableScanRDD.scala:326)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:319)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:283)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:79)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:47)
	at org.apache.spark.scheduler.Task.run(Task.scala:86)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:274)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect), 127.0.0.2/127.0.0.2:9042 (com.datastax.driver.core.exceptions.TransportException: [127.0.0.2/127.0.0.2] Cannot connect), 127.0.0.3/127.0.0.3:9042 (com.datastax.driver.core.exceptions.TransportException: [127.0.0.3/127.0.0.3] Cannot connect))
	at com.datastax.driver.core.ControlConnection.reconnectInternal(ControlConnection.java:233)
	at com.datastax.driver.core.ControlConnection.connect(ControlConnection.java:79)
	at com.datastax.driver.core.Cluster$Manager.init(Cluster.java:1424)
	at com.datastax.driver.core.Cluster.getMetadata(Cluster.java:403)
	at com.datastax.spark.connector.cql.CassandraConnector$.com$datastax$spark$connector$cql$CassandraConnector$$createSession(CassandraConnector.scala:156)
	... 24 more

Driver stacktrace:
	at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1454)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1442)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1441)
	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1441)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:811)
	at scala.Option.foreach(Option.scala:257)
	at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:811)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1667)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1622)
	at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1611)
	at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
	at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:632)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1890)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1903)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1916)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1930)
	at org.apache.spark.rdd.RDD$$anonfun$collect$1.apply(RDD.scala:912)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:358)
	at org.apache.spark.rdd.RDD.collect(RDD.scala:911)
	at org.apache.spark.sql.execution.SparkPlan.executeCollect(SparkPlan.scala:290)
	at org.apache.spark.sql.Dataset$$anonfun$org$apache$spark$sql$Dataset$$execute$1$1.apply(Dataset.scala:2193)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.Dataset.withNewExecutionId(Dataset.scala:2546)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$execute$1(Dataset.scala:2192)
	at org.apache.spark.sql.Dataset.org$apache$spark$sql$Dataset$$collect(Dataset.scala:2199)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2227)
	at org.apache.spark.sql.Dataset$$anonfun$count$1.apply(Dataset.scala:2226)
	at org.apache.spark.sql.Dataset.withCallback(Dataset.scala:2559)
	at org.apache.spark.sql.Dataset.count(Dataset.scala:2226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:244)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:308)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:294)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:846)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:511)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:468)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:382)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:354)
	at io.ne
```

**Comment by AkhilNairAmey** [comment] 2017-06-19 06:28
Just for a bit more info, how big is the table you're trying to load? Also am I reading this correctly in that you have 3 cassandra nodes all running on the localhost?

After this error occurs, can you get into the cluster with cqlsh? What does nodetool status return?

**Comment by AkhilNairAmey** [comment] 2017-06-19 06:28
And check Cassandra logs in case the problem is reading over the tombstone limit

**Comment by sdanielzafar** [comment] 2017-06-19 07:07
Hello again :)

The table is ~6500 rows and 48 columns. Yes that's right, it's silly but I was only given a single VM (2 cores) to play with for Cassandra. I can get into it with cqlsh. Here is the output of `nodetool status`
```
$ nodetool status
nodetool: Failed to connect to '127.0.0.1:7199' - ConnectException: 'Connection refused (Connection refused)'.
```

**Comment by AkhilNairAmey** [comment] 2017-06-19 07:13
Hi!

First couple hits on Google - have you set the `listen_address` and `broadcast_rpc_address` in the `cassandra.yaml`?

https://stackoverflow.com/questions/41776345/cassandra-failed-to-connect

**Comment by sdanielzafar** [comment] 2017-06-19 07:22
Here is what I have for those in `cassandra.yaml`
```
listen_address: localhost
...
rpc_address: 127.0.0.1
# rpc_interface: eth1
# rpc_interface_prefer_ipv6: false

# port for Thrift to listen for clients on
rpc_port: 9160

# RPC address to broadcast to drivers and other Cassandra nodes. This cannot
# be set to 0.0.0.0. If left blank, this will be set to the value of
# rpc_address. If rpc_address is set to 0.0.0.0, broadcast_rpc_address must
# be set.
# broadcast_rpc_address: 1.2.3.4
```

**Comment by sdanielzafar** [comment] 2017-06-19 15:12
So I've switched it to:
```
rcp_address: localhost
# rpc_interface: eth1
# rpc_interface_prefer_ipv6: false

# port for Thrift to listen for clients on
rpc_port: 9160

# RPC address to broadcast to drivers and other Cassandra nodes. This cannot
# be set to 0.0.0.0. If left blank, this will be set to the value of
# rpc_address. If rpc_address is set to 0.0.0.0, broadcast_rpc_address must be set.
broadcast_rpc_address: localhost
```
and still getting the same error.

**Comment by AkhilNairAmey** [comment] 2017-06-19 17:04
Did you restart Cassandra? This is just general networking now I think and not sparklyr, you might have some luck asking on stackoverflow?

**Comment by sdanielzafar** [comment] 2017-06-20 20:16
Yep, I did restart. Thanks for bearing with me, I've learned so much. For my understanding, why do you see this as being a networking issue?

**Comment by javierluraschi** [comment] 2017-06-30 18:42
Mostly answering questions and closing this issue, stackoverflow would be a good place to continue this discussion but hopefully this address most.

First, we've created a few wrappers making it easier to import data form any Spark package, the updated code is as follows:

```r
config <- spark_config()
config[["sparklyr.defaultPackages"]] <- c(
   "datastax:spark-cassandra-connector:2.0.0-RC1-s_2.11")

sc <- spark_connect(master = "local",
                    version = "2.1.0",
                    config = config)

spark_read_source(
  sc, "emp",
  "org.apache.spark.sql.cassandra",
  list(keyspace = "dev",
       table = "emp"))
```

From @renegademonkey:

>When bringing in databases from a certain Cassandra keyspace and table, can you at the same time filter the dataset, i.e. to only bring in some columns (i.e. using SQL-like SELECT commands)?

Yes, Sparl does support pushing predicates to remote sources, as least when supported by the source. However, `saprklyr` is greedy and by default loads everything into memory, you probably want to use `memory=FALSE`, as in:

```
spark_read_source(
  sc, "emp",
  "org.apache.spark.sql.cassandra",
  list(keyspace = "dev",
       table = "emp"),
  memory = FALSE)
```

From @prbhadra:

> How do we load frozen or any other Cassandra complex objects in a DF for further analysis?

Yes, even complex objects will be retrieved, I believe; however, they will be nested and maybe not very usable. If you can provide an example with the kind of complex objects your data contains and what you need to extract from them, we can suggest something more appropriate.

From @sdanielzafar:

I see this in the logs:

```
com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: localhost/127.0.0.1:9042 (com.datastax.driver.core.exceptions.TransportException: [localhost/127.0.0.1] Cannot connect)
```

It does seems to be the case that something needs to be tweaked in the cassandra configs, looks like @AkhilNairAmey might have already pointed out this. For that error, I would double check settings like `spark.cassandra.connection.host`, `spark.cassandra.connection.rpc.port`, etc. This seems to be like a good place to look at these settings: http://docs.datastax.com/en/archived/datastax_enterprise/4.5/datastax_enterprise/spark/sparkCassProps.html. I have limited time to support conenctivity issues with thrid party data providers through Spark; the stackoverflow community might give you a few more pointers.

**Closed by javierluraschi** 2017-06-30 18:42 UTC
Labels: data, question

**Comment by abdkumar** [comment] 2020-05-20 05:48
> @prbhadra This worked for me:
> 
> Install Cassandra, I followed (https://www.datastax.com/2012/01/working-with-apache-cassandra-on-mac-os-x):
> 
> ```
> curl -OL http://downloads.datastax.com/community/dsc.tar.gz
> tar -xzf dsc.tar.gz 
> cd dsc-cassandra-3.0.9/bin
> ./cassandra
> ```
> 
> Created some tables:
> 
> ```
> cd dsc-cassandra-3.0.9/bin
> ./cqlsh
> create keyspace dev with replication = {'class':'SimpleStrategy','replication_factor':1};
> use dev;
> create table emp (empid int primary key, emp_first varchar, emp_last varchar, emp_dept varchar);
> insert into emp (empid, emp_first, emp_last, emp_dept) values (1,'fred','smith','eng');
> ```
> 
> Now, from sparklyr:
> 
> ```
> library(sparklyr)
> 
> config <- spark_config()
> config[["sparklyr.defaultPackages"]] <- c(
>    "datastax:spark-cassandra-connector:2.0.0-RC1-s_2.11")
> 
> sc <- spark_connect(master = "local", version = "1.6.1", config = config)
> 
> df <- sparklyr:::spark_data_read_generic(
>   sc,
>   "org.apache.spark.sql.cassandra",
>   "format", list(
>     keyspace = "dev",
>     table = "emp"
> )) %>% invoke("load")
> 
> cassandra_tbl <- sparklyr:::spark_partition_register_df(
>   sc,
>   df,
>   name = "emp",
>   repartition = 0,
>   memory = FALSE)
> ```
> 
> Then, `cassandra_tbl` can be use as any other table with `ml` functions, `dplyr`, `DBI`, etc.
> 
> ```
> cassandra_tbl
> Source:   query [1 x 4]
> Database: spark connection master=local[8] app=sparklyr local=TRUE
> 
>   empid emp_dept emp_first emp_last
>   <int>    <chr>     <chr>    <chr>
> 1     1      eng      fred    smith
> ```
> 
> Make sure to match the Cassandra connection version with the Spark version, the full list is available here: https://spark-packages.org/package/datastax/spark-cassandra-connector
> 
> Notice that [spark_data_read_generic](https://github.com/rstudio/sparklyr/blob/ecba68f1c663253c1c83fdd5f2cbcad41158879c/R/data_interface.R#L306-L314) is a private function since it makes use of `invoke`, would be great to create a CRAN extension that wraps this functionality and makes it available to others, [sparkhello](https://github.com/javierluraschi/sparkhello) is a simple extension to `sparklyr` to get started.

@javierluraschi How do I connect to remote Cassandra using sparklyr? I'm note-getting solution anywhere?
