### ISSUE TITLE
Change columns names

### ISSUE THREAD

**Issue by igornoberto** [rstudio/sparklyr#900] opened 2017-08-04 20:16 UTC
```
df <- data.frame(old1 = LETTERS, old2 = 1)
df_tbl <- copy_to(sc,df,"df")

df_tbl <- df_tbl %>% dplyr::rename(old1 = new1, old2 = new2)
```

returns:

```
> head(df_tbl)
Error: `new1`, `new2` contains unknown variables
```

Is there an easy way to change the column names? since the regular R's funcitons doesn't work:

```
new_names <- c("new1", "new2")
names(df_tbl) <- new_names
colnames(df_tbl) <- new_names
```

---------

```
>sessionInfo()
R version 3.4.0 (2017-04-21)
other attached packages:
[1] sparklyr_0.6.0   dplyr_0.7.2.9000
```

**Comment by kevinykuo** [comment] 2017-08-04 20:45
@igornoberto right now you have to do 

```
df_tbl <- df_tbl %>%
  rename(new1 = old1) %>%
  rename(new2 = old2)
df_tbl
# # Source:   lazy query [?? x 2]
# # Database: spark_connection
#     new1  new2
#     <chr> <dbl>
# 1     A     1
# 2     B     1
# 3     C     1
# 4     D     1
# 5     E     1
# 6     F     1
# 7     G     1
# 8     H     1
# 9     I     1
# 10     J     1
# # ... with more rows
```

Ideally we'd like to do following but it's currently breaking:

```
df_tbl %>%
  rename(new1 = old1, new2 = old2)
# Error in names(select)[match(old_vars, vars)] <- new_vars : 
#   NAs are not allowed in subscripted assignments
```

You can track the issue at https://github.com/tidyverse/dplyr/issues/2860 and https://github.com/tidyverse/dplyr/issues/2896

Also related: https://github.com/rstudio/sparklyr/issues/678

**Comment by igornoberto** [comment] 2017-08-07 01:22
@kevinykuo 

I made the same question on stackoverflow, and user8371915 suggested to use `select`. And it worked.

https://stackoverflow.com/questions/45514906/sparklyr-change-columns-names-in-a-spark-dataframe

The solution:

```
> df_tbl %>% select(new1 = old1, new2 = old2)
# Source:   lazy query [?? x 2]
# Database: spark_connection
    new1  new2
   <chr> <dbl>
 1     A     1
 2     B     1
 3     C     1
 4     D     1
 5     E     1
 6     F     1
 7     G     1
 8     H     1
 9     I     1
10     J     1
# ... with 16 more rows
```

**Comment by kevinykuo** [comment] 2017-08-07 16:31
@igornoberto yep that works in this case; please keep in mind that `select()` only returns the columns specified, whereas `rename()` returns all columns of the dataframe with the specified one renamed, so if you have a dataframe with many columns but just want to rename a couple, `rename()` would likely be easier.

**Comment by kevinlzheng** [comment] 2017-08-16 15:27
To systematically change all column names, see suggestions from @user6910411 using select along with [.dots(setName]
(https://stackoverflow.com/questions/45622262/sparklyr-change-all-column-names-spark-dataframe). It worked for me.

**Comment by kevinykuo** [comment] 2017-08-16 20:07
Paging @lionel-... what would be the idiomatic tidyeval way to rename multiple columns with a character vector now that SE verbs are deprecated?

**Comment by lionel-** [comment] 2017-08-17 06:39
Since select/rename verbs now support character vectors, it should simply be

```r
x <- c(new1 = "cyl", new2 = "am")
rename(mtcars, !! x)
```

but it doesn't currently work. I have submitted an issue: https://github.com/tidyverse/dplyr/issues/3030.

In the meantime you can do it the usual way by turning your character vector to a list of symbols and splice it in the `rename()` call:

```r
rename(mtcars, !!! syms(x))
```

**Comment by hlendway** [comment] 2017-09-01 12:33
Odd, this works for me, it barked about id but when I put it in `` it worked.
tbl_cache(sc, 'taskrelation_archive')
taskRelation <- tbl(sc, 'taskrelation_archive')
taskRelation <- taskRelation %>% 
  rename(taskRelationId=`id`, ts = time_stamp)
> colnames(taskRelation)
[1] "taskRelationId" "relationid"     "taskid"         "iswhat"         "isdeleted"      "ts"

**Comment by kevinykuo** [comment] 2017-11-03 15:46
Confirmed fixed with devel `dplyr`. Thanks @lionel- !

**Closed by kevinykuo** 2017-11-03 15:46 UTC
Labels: dplyr
