### ISSUE TITLE
sdf_save_table does not work using spark 1.6.2 and hadoop 2.6

### ISSUE THREAD

**Issue by joscani** [rstudio/sparklyr#239] opened 2016-09-28 18:02 UTC
Hi.
I'm trying to upload an object made with using sdf_predict in a spark using sdf_save_table, but It doesn't work. However if I install spark 2.0 and hadoop 2.7 it work, but then sparkling  to use h2o sparkling-water does not work. My system is a i5core running a xubuntu 16.04 64 bits

**Comment by kevinushey** [comment] 2016-09-28 18:20
Can you please post the error message you're seeing?

**Comment by joscani** [comment] 2016-09-28 18:23
Of course. 

```
> sc <- spark_connect(master = "local")
> mtcars_tbl <- copy_to(sc, mtcars)
> partitions <- mtcars_tbl %>%
+    filter(hp >= 100) %>%
+    mutate(cyl8 = cyl == 8) %>%
+    sdf_partition(training = 0.5, test = 0.5, seed = 1099)
> fit <- partitions$training %>%
+    ml_linear_regression(response = "mpg", features = c("wt", "cyl"))
> summary(fit)
Call: ml_linear_regression(., response = "mpg", features = c("wt", "cyl"))

Deviance Residuals::
    Min      1Q  Median      3Q     Max 
-2.6881 -1.0507 -0.4420  0.4757  3.3858 

Coefficients:
            Estimate Std. Error t value  Pr(>|t|)    
(Intercept) 37.06670    2.76494 13.4059 2.981e-07 ***
wt          -2.30950    0.84748 -2.7252   0.02341 *  
cyl         -1.63955    0.58635 -2.7962   0.02084 *  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

R-Squared: 0.8665
Root Mean Squared Error: 1.799
> fit.rf <- partitions$training %>%
+    ml_random_forest(response= mpg~.)
> predrf <- sdf_predict(fit.rf)
> sdf_save_table(predrf, "predicciones")
Error: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelation.scala:154)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:106)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1.apply(InsertIntoHadoopFsRelation.scala:106)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:56)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation.run(InsertIntoHadoopFsRelation.scala:106)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult$lzycompute(commands.scala:58)
	at org.apache.spark.sql.execution.ExecutedCommand.sideEffectResult(commands.scala:56)
	at org.apache.spark.sql.execution.ExecutedCommand.doExecute(commands.scala:70)
	at org.apache.spark.sql.execution.SparkPlan$$anonfun$execute$5.appl
> 
```

**Comment by kevinushey** [comment] 2016-09-28 18:28
Thanks! I've reproduced this and it does seem to work with Spark 2.0.0, but not with Spark 1.6.2. I'll see if I can figure out what's going on.

**Comment by joscani** [comment] 2016-09-28 18:31
Thanks. Sparklyr  seems a nice a good project.

**Comment by kevinushey** [comment] 2016-09-28 18:42
In the Spark logs, I see:

```
java.io.IOException: Mkdirs failed to create file:/user/hive/warehouse/predicciones/_temporary/0/_temporary/attempt_201609281132_0039_m_000000_0 (exists=false, cwd=file:/Users/kevin)
```

It looks like this directory is used no matter what the `hive.metastore.warehouse.dir` is set to on the Hive context, so it's likely a bug in Spark <2.0.0 -- some discussion on StackOverflow [seems to echo that assertion](http://stackoverflow.com/questions/31985728/spark-on-embedded-mode-user-hive-warehouse-not-found).

I'll see if we can work around this.

**Comment by kevinushey** [comment] 2016-09-28 20:03
This should be worked around in the latest version of sparklyr, can you try installing it from GitHub and let us know if it works?

```
devtools::install_github('rstudio/sparklyr')
```

**Comment by kevinushey** [comment] 2016-09-28 21:22
Closing this as resolved; please re-open if you're still having trouble.

**Closed by kevinushey** 2016-09-28 21:22 UTC
