### ISSUE TITLE
Unable to load high dimension dataset

### ISSUE THREAD

**Issue by lalitnookala** [rstudio/sparklyr#242] opened 2016-09-30 17:24 UTC
So, I am using the data available on https://www.kaggle.com/c/digit-recognizer/download/train.csv. This dataset has 42000 rows and 785 columns (1 for label and 784 pixels.)

Now using Sparklyr I want to analyze this data. I have the following code written

```
install.packages("sparklyr")

library(sparklyr)
library(dplyr)
spark_install(version = "2.0.0")
spark <- spark_connect(master="local[*]",
                       version="2.0.0")
digit_df <- read.csv2(path='/path/to/downloaded/data/from/kaggle',header = TRUE, sep=',')
digit_tbl_spark <- sdf_copy_to(sc,x = digit_df)
# Comment the above 2 lines and execute the following.

digit_tbl_spark <- spark_read_csv(sc,'digit_df', 'file:///path/to/downloaded/data/from/kaggle',
                                  overwrite = TRUE) 
digit_tbl_show %>% show()

The output of show() is 

label pixel0 pixel1 pixel2 pixel3 pixel4 pixel5 pixel6 pixel7 pixel8 pixel9 pixel10 pixel11 pixel12 pixel13 pixel14 pixel15 pixel16
   <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>  <int>   <int>   <int>   <int>   <int>   <int>   <int>   <int>
1      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
2      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
3      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
4      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
5      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
6      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
7      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
8      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
9      0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
10     0      0      0      0      0      0      0      0      0      0      0       0       0       0       0       0       0       0
 ... with more rows, and 767 more variables: pixel17 <int>, pixel18 <int>, pixel19 <int>, pixel20 <int>, pixel21 <int>, pixel22 <int>,
  pixel23 <int>, pixel24 <int>, pixel25 <int>, pixel26 <int>, pixel27 <int>, pixel28 <int>, pixel29 <int>, pixel30 <int>, pixel31 <int>,
   pixel32 <int>, pixel33 <int>, pixel34 <int>, pixel35 <int>, pixel36 <int>, pixel37 <int>, pixel38 <int>, pixel39 <int>, pixel40 <int>,
   pixel41 <int>, pixel42 <int>, pixel43 <int>, pixel44 <int>, pixel45 <int>, pixel46 <int>, pixel47 <int>, pixel48 <int>, pixel49 <int>,
   pixel50 <int>, pixel51 <int>, pixel52 <int>, pixel53 <int>, pixel54 <int>, pixel55 <int>, pixel56 <int>, pixel57 <int>, pixel58 <int>,
   pixel59 <int>, pixel60 <int>, pixel61 <int>, pixel62 <int>, pixel63 <int>, pixel64 <int>, pixel65 <int>, pixel66 <int>, pixel67 <int>,
   pixel68 <int>, pixel69 <int>, pixel70 <int>, pixel71 <int>, pixel72 <int>, pixel73 <int>, pixel74 <int>, pixel75 <int>, pixel76 <int>,
   pixel77 <int>, pixel78 <int>, pixel79 <int>, pixel80 <int>, pixel81 <int>, pixel82 <int>, pixel83 <int>, pixel84 <int>, pixel85 <int>,
   pixel86 <int>, pixel87 <int>, pixel88 <int>, pixel89 <int>, pixel90 <int>, pixel91 <int>, pixel92 <int>, pixel93 <int>, pixel94 <int>,
   pixel95 <int>, pixel96 <int>, pixel97 <int>, pixel98 <int>, pixel99 <int>, pixel100 <int>, pixel101 <int>, pixel102 <int>,
   pixel103 <int>, pixel104 <int>, pixel105 <int>, pixel106 <int>, pixel107 <int>, pixel108 <int>, pixel109 <int>, pixel110 <int>,
   pixel111 <int>, pixel112 <int>, pixel113 <int>, pixel114 <int>, pixel115 <int>, pixel116 <int>, ...
```

Sparklyr is unable to read up a high dimension dataset. How do I know this? By trial and error: I chopped of the dataset to only 72 columns and the dataset was loaded correctly through sparklyr and show() displayed the correct output.

Can someone tell me what is going on?

Thanks

**Comment by kevinushey** [comment] 2016-09-30 18:16
Thanks for the bug report! It looks like there's something going wrong with our `collect()` implementation -- we receive the expected result when reading a single column from the table, but not when collecting the whole table in one go.

I'll try to see if I can figure out what's up. As a workaround, you can try collecting the dataset column-by-column with something like:

```R
col_names <- tbl_vars(digit_tbl)
columns <- lapply(col_names, function(col_name) {
  sdf_read_column(digit_tbl, col_name)
})
names(columns) <- col_names
digit_cl <- as_data_frame(columns)
```

Or even stacking up each pixel pixel value into a single column, with another column added as the label.

**Comment by kevinushey** [comment] 2016-09-30 19:08
As far as I can tell, this appears to be a bug in Spark itself. Even calling the `collect()` method directly returns the wrong result. From some local debugging:

```
Browse[3]> collected <- invoke(sdf, "collect")
Browse[3]> collected[[1]]
<jobj[802]>
  class org.apache.spark.sql.catalyst.expressions.GenericRowWithSchema
  [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0... <truncated>
```

Of course, the first row is _not_ filled with all zeroes. I'll try to verify this + generate a reproducible example and submit it upstream to the Spark team.

**Comment by lalitnookala** [comment] 2016-09-30 19:40
Thanks for looking into this so quickly. 

I will try your solution of having pixel data in one column and label as a separate column.

To give you more background on this: I am trying to execute PCA on this dataset.

pca_train_model <- digit_tbl_spark %>%select(-label) %>%ml_pca()

and when I tried to look at my explainedVariance(Spark v2.0.0) and its components( v1.6.2 or v2.0.0), it returns an Identity matrix for Components which makes sense since all the data is 0's. 

Hopefully this will help in more debugging.

On a positive note I downloaded dataset https://www.cms.gov/OpenPayments/Explore-the-Data/Dataset-Downloads.html#. "Complete 2014 Program Year Open Payments Dataset" which is a 6GB dataset and has 11176967 rows and 65 columns. This one loaded up into a Spark Dataframe and I was able to see the data through show() method just fine.

Thanks for this wonderful package and your quick response with the workaround.

Lalit

**Comment by kevinushey** [comment] 2016-09-30 21:18
I've just pushed a workaround for this particular issue -- could you try reinstalling `sparklyr` with:

```
devtools::install_github('rstudio/sparklyr')
```

and let us know if the issue is resolved?

**Comment by kevinushey** [comment] 2016-09-30 21:22
As an aside -- I do _not_ see this issue when using `SparkR`, so there must be something funky going on in `sparklyr` code somewhere. :/

**Comment by kevinushey** [comment] 2016-09-30 22:20
Scratch that; I was able to reproduce with `SparkR` after all. Filed a JIRA issue: https://issues.apache.org/jira/browse/SPARK-17752

**Comment by kevinushey** [comment] 2016-10-03 19:30
It looks like this is a bug in Spark 2.0.0 and Spark 1.6.2 -- hopefully, things will be fixed up in the next Spark release(s).

**Comment by lalitnookala** [comment] 2016-10-03 20:17
Kevin,
Collecting the data through show() command works fine with the code push you did. 

However, running the code from the website for PCA still does not return the expected output. Here is the code

devtools::install_github('rstudio/sparklyr')
library(sparklyr)
library(dplyr)
sc <- spark_connect(master="local", version="1.6.2")
digit_tbl_spark <- spark_read_csv(sc,'digit_df', 'file:///path/to/kaggle/hand/written/digits/data')
digit_tbl_spark %>% group_by(label) %>% summarize(count = n()) #This works fine
digit_tbl_spark %>%show() #Works with the changes pushed down on Friday

pca_train_model <- digit_tbl_spark %>%select(-label) %>%ml_pca()
pca_train_model$components #This does not return the right outputs.

Can you let me know what might be going on?

**Comment by lalitnookala** [comment] 2016-10-03 20:32
Ok. Hope it will.

Thanks,

Lalit S Nookala
*Senior Analyst*
International Software Systems Inc.
(P) 615-294-4723
(E) lalit.nookala@gmail.com

   - www.linkedin.com/in/lalitnookala/

**Comment by kevinushey** [comment] 2016-10-03 20:43
Thanks -- you're indeed right that something is still going wrong. It looks like there's an ugly bug in Spark where `collect()`, when called on a cached table, will silently replace all the returned data with zeroes. :/

You can work around this for now by supplying `memory = FALSE` to the `spark_read_csv()` call, e.g.

```
digit_tbl_spark <- spark_read_csv(sc, "digit_df", path, memory = FALSE)
```

**Comment by lalitnookala** [comment] 2016-10-03 20:44
I will try that tomorrow and let you know my results.

**Comment by javierluraschi** [comment] 2017-08-17 20:45
Using Spark 2.0.0 or 2.2.0 and `sparklyr 0.6` this seems to be working now, 

```
spark <- spark_connect(master="local[*]", version="2.0.0")
digit_tbl_spark <- spark_read_csv(sc, 'digit_df', '/Users/javierluraschi/Downloads/train.csv', overwrite = TRUE) 
digit_tbl_spark %>% select(pixel324)
# Source:   lazy query [?? x 1]
# Database: spark_connection
   pixel324
      <int>
 1      253
 2        0
 3        0
 4        0
 5        0
 6        0
 7      213
 8      121
 9       20
10      253
# ... with more rows
```

**Closed by javierluraschi** 2017-08-17 20:45 UTC
Labels: serialization
