### ISSUE TITLE
Failed while connecting to sparklyr to port (8880)

### ISSUE THREAD

**Issue by hongqp** [rstudio/sparklyr#562] opened 2017-03-17 15:56 UTC
When I run the script on rstudio-server (web):

library(sparklyr)
library(dplyr)
library(DBI)
sc <- spark_connect(master="yarn-client", method = c("shell"),config=spark_config(), app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())

I got a Error: 

Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (3717): Gateway in port (8880) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/home/udpclient01/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 3717

---- Output Log ----
17/03/17 23:24:23 INFO sparklyr: Session (3717) starting
17/03/17 23:24:23 INFO sparklyr: Registering session (3717) into gateway port (8880)
17/03/17 23:24:23 INFO sparklyr: Waiting for registration of (3717) into gateway port (8880)
17/03/17 23:24:23 INFO sparklyr: Finished registration of session (3717) into gateway port (8880) with status (0)

---- Error Log ----
> sparklyr::spark_home_dir()
NULL
> sc <- spark_connect(master="yarn-client", method = c("shell"),config=spark_config(), app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (5281): Gateway in port (8880) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/home/udpclient01/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 8880, 5281

---- Output Log ----
17/03/17 23:27:43 INFO sparklyr: Session (5281) starting
17/03/17 23:27:43 INFO sparklyr: Registering session (5281) into gateway port (8880)
17/03/17 23:27:43 INFO sparklyr: Waiting for registration of (5281) into gateway port (8880)
17/03/17 23:27:43 INFO sparklyr: Finished registration of session (5281) into gateway port (8880) with status (0)

---- Error Log ----

but the same script is working well on the R command line on the same server.
Could you tell me what can I do to connect to spark(yarn)?

**Comment by kevinykuo** [comment] 2017-03-17 21:44
Is your cluster Kerberized? If so try running `kinit` in the RStudio shell (through the RStudio Server web UI) before connecting.

**Comment by hongqp** [comment] 2017-03-20 09:02
@kevinykuo ,
I try key in 'kinit' in the RStudio shell(web UI) and run , but get "Error: object 'kinit' not found".
so what command should I use?

I was surprised that why the same R-script can run well on R-command line(through putty), but can't run well on RStudio-server?

**Comment by hongqp** [comment] 2017-03-20 09:17
I try to change other port like this:

config <- spark_config()
config$sparklyr.gateway.port = 10000
library(sparklyr)
library(dplyr)
library(DBI)
sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())

but get the same Error:

Error in force(code) : 
  Failed while connecting to sparklyr to port (10000) for sessionid (8150): Gateway in port (10000) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/home/udpclient01/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 10000, 8150


---- Output Log ----
17/03/20 17:15:17 INFO sparklyr: Session (8150) starting

---- Error Log ----

**Comment by javierluraschi** [comment] 2017-03-21 17:01
@hongqp which version are you running? A few days ago a change went in to improve 2X-3X the `spark_connect` speed, this change had a regression that was fixed yesterday, if you are using the `devel` branch of `sparklyr` I would retry with the latest version. If you are using the `CRAN` version of `sparklyr`, let us know to suggest something different.

**Comment by hongqp** [comment] 2017-03-23 08:53
@kevinykuo ,thanks，and I try to run "kinit" in the tool-->shell (RStudio-server)
but get  : 
bash-4.1$ kinit
kinit: Cannot contact any KDC for realm 'EXAMPLE.COM' while getting initial credentials

@javierluraschi ,thanks，the version fo sparklyr I installed is 0.5.3-9002.It's seems that RStudio-server can't get respond from gateway, but R command-line can. Is there any configuration should I configure before connect to spark？

**Comment by javierluraschi** [comment] 2017-03-23 23:34
@hongqp could you try this instead?

```
config <- spark_config()
config$sparklyr.gateway.port = 10000
config$sparklyr.gateway.connect.timeout = 1
library(sparklyr)
library(dplyr)
library(DBI)
sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())
```

If that doesn't work would yo try:

```
config <- spark_config()
config$sparklyr.gateway.port = 10000
config$sparklyr.gateway.connect.timeout = 1
config$sparklyr.gateway.start.wait = 1000
library(sparklyr)
library(dplyr)
library(DBI)
sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())
```

If that works, I can adjust the timeouts appropriately in `sparklyr`. Thanks!

**Comment by hongqp** [comment] 2017-03-24 02:40
@javierluraschi , I try two script, none of them can work. Result is follow:

```
> config <- spark_config()
> config <- spark_config()
> config$sparklyr.gateway.port = 10000
> config$sparklyr.gateway.connect.timeout = 1
> library(sparklyr)
> library(dplyr)
> library(DBI)
> sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())
Error in force(code) : 
  Failed while connecting to sparklyr to port (10000) for sessionid (4905): Gateway in port (10000) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/home/udpclient01/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 10000, 4905


---- Output Log ----
17/03/24 09:59:17 INFO sparklyr: Session (4905) starting
17/03/24 09:59:17 INFO sparklyr: Registering session (4905) into gateway port (10000)
17/03/24 09:59:17 INFO sparklyr: Waiting for registration of (4905) into gateway port (10000)
17/03/24 09:59:17 INFO sparklyr: Finished registration of session (4905) into gateway port (10000) with status (0)

---- Error Log ----
```



```
> config <- spark_config()
> config$sparklyr.gateway.port = 10000
> config$sparklyr.gateway.connect.timeout = 1
> config$sparklyr.gateway.start.wait = 1000
> library(sparklyr)
> library(dplyr)
> library(DBI)
> sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())
Error in force(code) : 
  Failed while connecting to sparklyr to port (10000) for sessionid (4745): Gateway in port (10000) did not respond.
    Path: /usr/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/home/udpclient01/R/x86_64-pc-linux-gnu-library/3.3/sparklyr/java/sparklyr-2.0-2.11.jar', 10000, 4745


---- Output Log ----
17/03/24 10:00:11 INFO sparklyr: Session (4745) starting
17/03/24 10:00:11 INFO sparklyr: Registering session (4745) into gateway port (10000)
17/03/24 10:00:11 INFO sparklyr: Waiting for registration of (4745) into gateway port (10000)
17/03/24 10:00:11 INFO sparklyr: Finished registration of session (4745) into gateway port (10000) with status (0)

---- Error Log ----

```

Could there a possibility that the problem is not on sparklyr, but between sparklyr and Rstudio server, or just  butween Rstudio server and spark-yarn need something to be configured ?
Could you please kindly to give me some R-script to test that?

**Comment by Vonisoa** [comment] 2017-03-24 06:08
I have the same trouble by spaecifting the driver memory.
First time I only use
`sc<-spark_connect(master = "local[2]")`
But when I try this, I get the same error
`sc <- spark_connect(master = "local[*]",
                    config = list("sparklyr.shell.driver-memory"="2g"))`
Maybe that can help.

**Comment by hongqp** [comment] 2017-03-27 02:19
@Vonisoa ,Thanks. 
I try both(Specified memory & Unspecified memory), but none of them can work...
Is there any other way to connect to spark-yarn through RStudio-Server？

**Comment by javierluraschi** [comment] 2017-03-28 23:47
@hongqp Is this a regression? Can you connect correctly using the CRAN version of `sparklyr` on `0.5.3`?

**Comment by javierluraschi** [comment] 2017-03-29 00:07
@hongqp Also, why use port `10000`? `ThriftServer` usually runs on this port, so I wonder if the default `8880` is any better.

**Comment by albit3** [comment] 2017-04-01 20:59
I'm getting a similar error after a fresh install of sparklyr package:

> library(sparklyr)
> sc <- spark_connect(master = "local")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (2477): Gateway in port (8880) did not respond.
    Path: /Users/Albit/Library/Caches/spark/spark-1.6.2-bin-hadoop2.6/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --jars, '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/spark-csv_2.11-1.3.0.jar','/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/commons-csv-1.1.jar','/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/univocity-parsers-1.5.1.jar', '/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-1.6-2.10.jar', 8880, 2477

**Comment by albit3** [comment] 2017-04-01 22:32
I tried running the following code posted by @hongqp :

config <- spark_config()
config$sparklyr.gateway.port = 10000
config$sparklyr.gateway.connect.timeout = 1
library(sparklyr)
library(dplyr)
library(DBI)
sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())

But I get the following error:

Error in validate_java_version(spark_home) : 
  Java version1.6.0.65 detected but 1.7+ is required. Please download and install Java from https://www.java.com/en/



So then I updated the Java version and confirmed the update in Macbook terminal:

/Library/Internet\ Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java -version 
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)


I then restarted the Rsession but I still get the same error indicating that I have Java version 1.6.0.65

**Comment by albit3** [comment] 2017-04-02 01:12
I was able to fix this issue by installing the latest Java version (jdk-8u121-macosx-x64.dmg) from here:

http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html

I check if the latest version was installed properly with "java -version" command in mac terminal:

java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)

This fixed the both problems (1 and 2) when trying the "sc <- spark_connect(master = "local")"  command in R:

1)Error in force(code) :
Failed while connecting to sparklyr to port (8880) for sessionid (3717): Gateway in port (8880) did not respond

2)Error in validate_java_version(spark_home) :
Java version1.6.0.65 detected but 1.7+ is required. Please download and install Java from

Hope this works for you as well!

Albit

**Comment by asobe** [comment] 2017-04-07 10:47
Hello - i get the exact same behavior as @hongqp both on RStudio and shell. 
```
 sc <- spark_connect(master="yarn-client", version="1.6.0", config=config)
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (6283): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/CDH-5.9.1-1.cdh5.9.1.p0.4/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --jars, '/home/anita.sobe/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/spark-csv_2.11-1.3.0.jar','/home/anita.sobe/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/commons-csv-1.1.jar','/home/anita.sobe/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/univocity-parsers-1.5.1.jar', '/home/anita.sobe/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/sparklyr-1.6-2.10.jar', 8880, 6283


---- Output Log ----
17/04/07 06:39:44 INFO sparklyr: Session (6283) starting
17/04/07 06:39:44 INFO sparklyr: Registering session (6283) into gateway port (8880)
17/04/07 06:39:44 INFO sparklyr: Waiting for registration of (6283) into gateway port (8880)
17/04/07 06:39:44 INFO sparklyr: Finished registration of session (6283) into gateway port (8880) with status (0)
---- Error Log ----
```
Cloudera CDH5.9.1, java 1.8.121, RHEL 7.1
Cluster is Kerberized, Yarn HA. I have a valid Kerberos ticket.
Spark-submit works outside of sparklyr. 
I tried the github version as well as the cran version of sparklyr.

**Comment by tcederquist** [comment] 2017-04-25 05:37
Almost same error as @asobe, @hongqp, just different output log entries - version: jdk1.8.0_92, sparklyr version: 0.5.3.9005, rhel7.3, rstudio 0.99.896, r:3.3.2. spark-shell returns scala prompt. Kerberos environment. cloudera:CDH-5.8.4-1.cdh5.8.4.p2167.2267
```
sc <- spark_connect(master = "yarn-client", config= config, version = "1.6.2")
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (3971): Gateway in port (8880) did not respond.
    Path: /opt/cloudera/parcels/CDH-5.8.4-1.cdh5.8.4.p2167.2267/lib/spark/bin/spark-submit
    Parameters: --class, sparklyr.Backend, --jars, '/usr/lib64/microsoft-r/3.3/lib64/R/library/sparklyr/java/spark-csv_2.11-1.3.0.jar','/usr/lib64/microsoft-r/3.3/lib64/R/library/sparklyr/java/commons-csv-1.1.jar','/usr/lib64/microsoft-r/3.3/lib64/R/library/sparklyr/java/univocity-parsers-1.5.1.jar', '/usr/lib64/microsoft-r/3.3/lib64/R/library/sparklyr/java/sparklyr-1.6-2.10.jar', 8880, 3971
    Log: /tmp/Rtmp0ekCQr/file2ab97124b295_spark.log


---- Output Log ----
17/04/25 01:23:19 INFO yarn.Client: Application report for application_1491107543422_10989 (state: ACCEPTED)
17/04/25 01:23:20 INFO yarn.Client: Application report for application_1491107543422_10989 (state: ACCEPTED)
17/04/25 01:23:21 INFO yarn.Client: Application report for application_1491107543422_10989 (state: ACCEPTED)
...
17/04/25 01:24:08 INFO yarn.Client: Application report for application_1491107543422_10989 (state: ACCEPTED)

---- Error Log ----
```

**Comment by asobe** [comment] 2017-05-02 10:38
@tcederquist : For you it looks like Yarn is waiting to assign some resources - you should maybe increase the timeouts as suggested in one of the above comments.

@javierluraschi Is there any way to debug what's going on in the connect part? i.e. get some more output when connecting to the gateway? Thanks.

**Comment by javierluraschi** [comment] 2017-05-10 08:39
@asobe to troubleshoot, is worth mentioning that from r, `sparklyr` submits an Spark application/backend that listens to port `8880` for remote commands, then the r session connects to this server and proxies all Spark commands.

On the backend, you can take a look at https://github.com/rstudio/sparklyr/blob/471aab077d9b83ee770d26067aa20e63dfc7545d/java/backend.scala#L399, which is the last line you see on your log, then the backend loops indefinitely until the r session connects, you can see this here: https://github.com/rstudio/sparklyr/blob/471aab077d9b83ee770d26067aa20e63dfc7545d/java/backend.scala#L241-L243 while waiting for a socket connection here: https://github.com/rstudio/sparklyr/blob/471aab077d9b83ee770d26067aa20e63dfc7545d/java/backend.scala#L254-L255

On the client, we try to stablish this connetion here: https://github.com/rstudio/sparklyr/blob/master/R/spark_shell.R#L264-L288 and more specifically here: https://github.com/rstudio/sparklyr/blob/5aff14dd08f05e4291ec837f5912b1d624b78d2f/R/spark_gateway.R#L14-L19

IIf you have time to troubleshoot this together, find me in gitter: https://gitter.im/rstudio/sparklyr or shoot me an email to javier at rstudio.com.

**Comment by Jerome3590** [comment] 2017-05-24 02:58
I have the same issue..Windows 10. Appears to be something with Java and .jar file.
<img width="442" alt="rstudio_spark setup" src="https://cloud.githubusercontent.com/assets/9680556/26385104/44a46974-400b-11e7-8e5c-1f274e5218bf.PNG">

**Comment by praveenmohan1979** [comment] 2017-05-31 13:10
@javierluraschi 
I face the same error described by @hongqp and others.

The same code works on the terminal but rstudio continues to throw this error despite following many suggestions in this forum.

sc <- spark_connect(master="yarn-client", method = c("shell"),config=config, app_name = "sparklyr",version="2.0.0", extensions = sparklyr::registered_extensions())

Error in force(code) : 
  Failed while connecting to sparklyr to port (10000) for sessionid (9960): Gateway in port (10000) did not respond.
    Path: /opt/cloudera/parcels/SPARK2-2.0.0.cloudera2-1.cdh5.7.0.p0.118100/lib/spark2/bin/spark-submit
    Parameters: --class, sparklyr.Backend, '/opt/cloudera/parcels/Anaconda-4.0.0/envs/r/lib/R/library/sparklyr/java/sparklyr-2.0-2.11.jar', 10000, 9960


---- Output Log ----
17/05/31 12:14:13 INFO sparklyr: Session (9960) starting
17/05/31 12:14:13 INFO sparklyr: Registering session (9960) into gateway port (10000)
17/05/31 12:14:13 INFO sparklyr: Waiting for registration of (9960) into gateway port (10000)
17/05/31 12:14:13 INFO sparklyr: Finished registration of session (9960) into gateway port (10000) with status (0)

Has any one been able to find a resolution? Pls advise. 

Cheers

**Comment by asobe** [comment] 2017-05-31 13:27
@javierluraschi @praveenmohan1979 @hongqp 
The reason was that ipv6 was enabled on this node and hence somehow the Socket has issues to start up.

**Comment by javierluraschi** [comment] 2017-06-21 17:19
@praveenmohan1979 when you say that everything works via terminal, do you mean by launching R from the terminal on the same machine where RStudio is installed? It would be a big difference if you are connecting to the master node and then launching the session from there while RStudio is on a separate node.

As @tcederquist mentioned, we found out during a support request that some cluster override the `yarn-client` setting to run under `yarn-cluster`, when this happens, an error similar to this ones would surface since the rsession would fail to reach (on the correct node) the sparklyr backend. If you could all provide as many details on your cluster setup, it would help me troubleshoot this one.

**Comment by javierluraschi** [comment] 2017-07-07 20:50
Long investigation over https://github.com/rstudio/sparklyr/issues/801 shows that one problem could be an incorrect value for the `JAVA_HOME` environment variable. Hard to tell how many of users in this issue will benefit from double checking `JAVA_HOME`; regardless, since there is low activity in this issue, closing.

If someone is willing to troubleshoot their connection issue thoroughly, please open a new one to help you out, thank you!

**Closed by javierluraschi** 2017-07-07 20:50 UTC
Labels: connection
