### ISSUE TITLE
`ml_logistic_regression()` throws error regarding null values even after using na.omit

### ISSUE THREAD

**Issue by JosiahParry** [rstudio/sparklyr#65] opened 2016-07-01 17:40 UTC
Printed are the first 10 rows of data 

``` r
loan_status loan_amnt int_rate grade emp_length home_ownership annual_inc   age
         <int>     <int>    <dbl> <chr>      <int>          <chr>      <dbl> <int>
1            0      5000    10.65     B         10           RENT      24000    33
2            0      2400       NA     C         25           RENT      12252    31
3            0     10000    13.49     C         13           RENT      49200    24
4            0      5000       NA     A          3           RENT      36000    39
5            0      3000       NA     E          9           RENT      48000    24
6            0     12000    12.69     B         11            OWN      75000    28
7            1      9000    13.49     C          0           RENT      30000    22
8            0      3000     9.91     B          3           RENT      15000    22
9            1     10000    10.65     B          3           RENT     100000    28
10           0      1000    16.29     D          0           RENT      28000    22
```

`spark_logit_loan <- loan_data_tbl %>% ml_logistic_regression(response = "loan_status", features = c("loan_amnt", "age", "emp_length"))`

This throws error. I then used `loan_data_tbl %>% na.omit() %>% ml_logistic_regression()` same error. Is this because of variable class? If so there needs to be documentation about how to change the classes. 

Data and analysis I used here: https://github.com/JosiahParry/sparklyr_exploration

**Comment by slopp** [comment] 2016-07-01 18:37
Josiah - interesting test analysis. This error isn't because of the variable class, but is caused by NA values in emp_length. The second error is because na.omit() is not a known function in Spark (though it may be worth implementing). In your case this will work:

```
loan_data_tbl %>% 
            filter(emp_length>=0)  %>% 
            ml_logistic_regression(response = "loan_status",
                                                features = c("loan_amnt", "age", "emp_length"))
```

For your wine example, in addition to creating  a binary variable with dplyr's mutate, you could also use one of Sparks feature transformers:

```
fit <- wine_tbl %>% 
  sdf_mutate(type_binary = ft_string_indexer("type")) %>% 
  ml_linear_regression(response = "quality",
                                         features = c("pH", "alcohol", "density", "type_binary"))

fit_base <- lm(quality ~ pH+alcohol+density+type, data=wine)

fit
fit_base
```

**Comment by JosiahParry** [comment] 2016-07-01 22:39
okay, thank you for the clarification. I was reading the documentation for `ft_string_indexer()` and I thought that it would create values such as 0, 1, 2, ... etc. I will try this. 

Also, important to me was the output of the regressions. I couldn't find significance levels in the output of the model. Maybe I missed them.

**Comment by kevinushey** [comment] 2016-07-01 23:09
To the best of my knowledge, that information won't be available until Spark 2.0.0, and that will be in the `GeneralizedLinearRegression` class (as opposed to the `LogisticRegression` class, which we currently use)

https://spark.apache.org/docs/2.0.0-preview/api/scala/index.html#org.apache.spark.ml.classification.BinaryLogisticRegressionSummary

https://spark.apache.org/docs/2.0.0-preview/api/scala/index.html#org.apache.spark.ml.regression.GeneralizedLinearRegressionSummary

It seems unfortunate that there is this fracturing of APIs, but it looks like they support different use cases. (For example, the `LogisticRegression` model allows for elastic-net type models; the `GeneralizedLinearRegression` model allows one to specify the model family)

We'll have to think about how to best accommodate this.

**Comment by javierluraschi** [comment] 2016-07-22 06:43
Per Kevin's comment, dependent on Spark 2.0.0 release. Marking as feature request.

**Comment by kevinushey** [comment] 2016-09-28 22:36
FWIW, we do now have a method for `na.omit()` that should work with Spark DataFrames.

**Comment by JosiahParry** [comment] 2016-10-03 20:50
Beautiful, I'll have to play with it!

**Closed** 2018-01-17 15:44 UTC
Labels: featurerequest, ml
