### ISSUE TITLE
Spaces in factor levels cause problems with ml_*() functions

### ISSUE THREAD

**Issue by richierocks** [rstudio/sparklyr#619] opened 2017-04-14 14:09 UTC
To reproduce:

```r
library(dplyr)
library(sparklyr)
data(diamonds, package = "ggplot2")

sc <- spark_connect("local")
diamonds_tbl <- copy_to(sc, diamonds)

feature_cols <- diamonds_tbl %>% 
  colnames() %>% 
  setdiff("price")
diamonds_tbl %>% 
  ml_gradient_boosted_trees("price", feature_cols)
##  Error: org.apache.spark.sql.AnalysisException: cannot resolve 'cut_Very' given input columns: 
##    [cut_Ideal, cut_Good, clarity, cut_Fair, x, cut_Very Good, cut_Premium, price, depth, table, z, cut, y, carat, color]
```

The problem seems to be related to the factor level `Very Good` for the `cut` column.

**Comment by kevinykuo** [comment] 2017-04-14 18:17
Unable to reproduce with Spark 2.1.0

```
diamonds_tbl <- copy_to(sc, diamonds)
feature_cols <- diamonds_tbl %>% 
  colnames() %>% 
  setdiff("price")
model <- diamonds_tbl %>% 
  ml_gradient_boosted_trees("price", feature_cols)
summary(model)
# Length Class      Mode       
# features                    23     -none-     character  
# response                     1     -none-     character  
# max.bins                     1     -none-     numeric    
# max.depth                    1     -none-     numeric    
# trees                       20     -none-     list       
# data                         2     spark_jobj environment
# ml.options                   6     ml_options list       
# categorical.transformations  3     -none-     environment
# model.parameters             5     -none-     list       
# .call                        4     -none-     call       
# .model                       2     spark_jobj environment
```

**Comment by richierocks** [comment] 2017-04-14 18:34
@kevinykuo I was using Spark 2.0.2.

**Comment by duttashi** [comment] 2017-07-03 06:13
@richierocks, Unable to reproduce with Spark 2.0.2
@javierluraschi I do not think this is a spark limitation

```
> spark_installed_versions()
  spark hadoop                       dir
1 1.6.2    2.6 spark-1.6.2-bin-hadoop2.6
2 2.0.2    2.7 spark-2.0.2-bin-hadoop2.7
3 2.1.0    2.7 spark-2.1.0-bin-hadoop2.7
> sc <- spark_connect(master = "local", version="2.0.2")
> library(dplyr)
> library(ggplot2)
> diamonds_tbl <- copy_to(sc, diamonds)
> feature_cols <- diamonds_tbl %>% 
+   colnames() %>% 
+   setdiff("price")
> model <- diamonds_tbl %>% 
+   ml_gradient_boosted_trees("price", feature_cols)
* No rows dropped by 'na.omit' call
> summary(model)
                            Length Class      Mode       
features                    23     -none-     character  
response                     1     -none-     character  
max.bins                     1     -none-     numeric    
max.depth                    1     -none-     numeric    
trees                       20     -none-     list       
data                         2     spark_jobj environment
ml.options                   6     ml_options list       
categorical.transformations  3     -none-     environment
model.parameters             5     -none-     list       
.call                        4     -none-     call       
.model                       2     spark_jobj environment
``` 
My session info is 

```
> sessionInfo()
R version 3.3.3 (2017-03-06)
Platform: i386-w64-mingw32/i386 (32-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

**Comment by kevinykuo** [comment] 2017-08-01 21:14
I can reproduce in Spark 1.6.3 and confirm that 2.0.2+ works OK. I don't think we should do anything like sanitizing data in `ml_` functions here. Closing...

**Closed by kevinykuo** 2017-08-01 21:14 UTC
Labels: ml, spark limitation
