### ISSUE TITLE
can't predict directly from ml_kmeans model: Error in eval(expr, envir, enclos) :    argument "newdata" is missing, with no default

### ISSUE THREAD

**Issue by MarcinKosinski** [rstudio/sparklyr#172] opened 2016-08-16 11:22 UTC
[Session info included below. I am using the newest possible devel version] 

Your documentation states that you can predict directly from fitted model http://spark.rstudio.com/mllib.html#k-means_clustering

````{R}
library(sparklyr)
library(ggplot2)
sc <- 
library(dplyr)
iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)
iris_tbl


kmeans_model <- iris_tbl %>%
  select(Petal_Width, Petal_Length) %>%
  ml_kmeans(centers = 3)

# print our model fit
print(kmeans_model)


# predict the associated class
predicted <- predict(kmeans_model)
table(predicted, iris$Species)
````

which might be true for local computations but for fitted model on YARN cluster I get this

````{R}
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> iris_tbl <- copy_to(sc, iris, "iris", overwrite = TRUE)
The following columns have been renamed:
- 'Sepal.Length' => 'Sepal_Length' (#1)
- 'Sepal.Width'  => 'Sepal_Width'  (#2)
- 'Petal.Length' => 'Petal_Length' (#3)
- 'Petal.Width'  => 'Petal_Width'  (#4)
> iris_tbl
Source:   query [?? x 5]
Database: spark connection master=yarn app=sparklyr local=FALSE

   Sepal_Length Sepal_Width Petal_Length Petal_Width  Species
          <dbl>       <dbl>        <dbl>       <dbl>    <chr>
1           5.1         3.5          1.4         0.2 "setosa"
2           4.9         3.0          1.4         0.2 "setosa"
3           4.7         3.2          1.3         0.2 "setosa"
4           4.6         3.1          1.5         0.2 "setosa"
5           5.0         3.6          1.4         0.2 "setosa"
6           5.4         3.9          1.7         0.4 "setosa"
7           4.6         3.4          1.4         0.3 "setosa"
8           5.0         3.4          1.5         0.2 "setosa"
9           4.4         2.9          1.4         0.2 "setosa"
10          4.9         3.1          1.5         0.1 "setosa"
# ... with more rows
> 
> 
> kmeans_model <- iris_tbl %>%
+   select(Petal_Width, Petal_Length) %>%
+   ml_kmeans(centers = 3)
> 
> # print our model fit
> print(kmeans_model)
K-means clustering with 3 clusters

Cluster centers:
  Petal_Width Petal_Length
1    0.246000     1.462000
2    2.037500     5.595833
3    1.342308     4.269231
> 
> 
> # predict the associated class
> predicted <- predict(kmeans_model)
Error in eval(expr, envir, enclos) : 
  argument "newdata" is missing, with no default
> table(predicted, iris$Species)
Error in table(predicted, iris$Species) : object 'predicted' not found
> sessionInfo()
R version 3.3.0 (2016-05-03)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8      
 [8] LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0    sparklyr_0.3.4

loaded via a namespace (and not attached):
 [1] readr_1.0.0     lazyeval_0.2.0  magrittr_1.5    R6_2.1.2        assertthat_0.1  rprojroot_1.0-2 DBI_0.5         tools_3.3.0     withr_1.0.2     tibble_1.1      Rcpp_0.12.6     digest_0.6.10  
> sc
$master
[1] "yarn"

$method
[1] "shell"

$app_name
[1] "sparklyr"

$config
$config$default
$config$default$spark.submit.deployMode
[1] "client"

$config$default$spark.yarn.keytab
[1] "opt/wpusers/mkosinski/mkosinski.keytab"

$config$default$spark.yarn.principal
[1] "mkosinski@AD.WP-SA.PL"

$config$default$spark.executor.instances
[1] 20

$config$default$spark.executor.memory
[1] "2G"

$config$default$spark.executor.cores
[1] 4

$config$default$spark.driver.memory
[1] "4G"



$spark_home
[1] "/opt/spark-2.0.0-bin-hadoop2.6"

$backend
        description               class                mode                text              opened            can read           can write 
"->localhost:36310"          "sockconn"                "wb"            "binary"            "opened"               "yes"               "yes" 

$monitor
        description               class                mode                text              opened            can read           can write 
"->localhost:53100"          "sockconn"                "a+"              "text"            "opened"               "yes"               "yes" 

$output_file
[1] "/tmp/Rtmple1tNk/file1834d0aade_spark.log"

$spark_context
<jobj[4]>
  class org.apache.spark.SparkContext
  org.apache.spark.SparkContext@7f730d64

$java_context
<jobj[5]>
  class org.apache.spark.api.java.JavaSparkContext
  org.apache.spark.api.java.JavaSparkContext@13e1b318

$hive_context
<jobj[8]>
  class org.apache.spark.sql.SparkSession
  org.apache.spark.sql.SparkSession@2461d5cb

attr(,"class")
[1] "spark_connection"       "spark_shell_connection" "DBIConnection"         
````

**Comment by kevinushey** [comment] 2016-08-16 17:11
Sorry, this was a recent regression -- when `newdata` is unspecified it should be drawn from the original data used to fit the model, but it looks like this isn't being done now. I think this will be a simple fix.

**Comment by kevinushey** [comment] 2016-08-16 17:14
Should be resolved with https://github.com/rstudio/sparklyr/commit/b76016eed88aefc7bc13499c1a8cd9d6b9886a52; thanks for reporting!

**Closed by kevinushey** 2016-08-16 17:14 UTC
