### ISSUE TITLE
ml_decision_tree failed to compile

### ISSUE THREAD

**Issue by monicarodguev** [rstudio/sparklyr#437] opened 2017-01-18 22:49 UTC
Hello guys,

I'm training a decision tree. My dataframe has 100 rows and 2473 columns. The code I'm using is the following:

```
arbol <- base %>%
  ml_decision_tree(BGI ~ . -var1-var2-var3, type = "classification")
```

But the job doesn't compile, the error I get is the following:

`Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 8.0 failed 1 times, most recent failure: Lost task 0.0 in stage 8.0 (TID 8, localhost): java.util.concurrent.ExecutionException: java.lang.Exception: failed to compile: org.codehaus.janino.JaninoRuntimeException: Code of method "(Lorg/apache/spark/sql/catalyst/InternalRow;)Z" of class "org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificPredicate" grows beyond 64 KB`

I'm running spark locally. Please let me know if any other information is needed. Thanks for your help.

Bests.

**Comment by javierluraschi** [comment] 2017-01-19 18:57
@monicarodguev See https://github.com/rstudio/sparklyr/issues/264, can you try reducing the number of columns? Say with something like:

```{r}
arbol <- base %>%
  select(BGI, var1, var2, var3) %>%
  ml_decision_tree(BGI ~ . -var1-var2-var3, type = "classification")
```

**Comment by monicarodguev** [comment] 2017-01-19 19:05
@javierluraschi just to confirm if I am getting it right: in the select sentence should I include all the variables I want to have in the model? Or just the ones I want to exclude?

**Comment by javierluraschi** [comment] 2017-01-19 23:57
@monicarodguev The ones you want in the model

**Comment by monicarodguev** [comment] 2017-01-20 20:48
Well in fact I would like to test with near 2.4k variables. Do you think is there any limitation in the number of input variables?

**Comment by javierluraschi** [comment] 2017-01-21 00:01
@monicarodguev we've experienced some column limitations in Spark `1.6.x`; therefore, I would highly recommend using Spark `2.x.x`. For instance, by connecting as:

```
sc <- spark_connect(master = "local", version = "2.1.0")
```

**Comment by dsblr** [comment] 2017-02-21 04:11
@javierluraschi 
I am using ml_random_forest for a classification model building. Could you please help me with the model parameter to control the **sample size**

**Comment by javierluraschi** [comment] 2017-08-24 18:06
dsblr issues is addressed in 377

@monicarodguev I can reproduce your issue as follows. The problem here seems to be in Spark itself, not `sparklyr`, 

```r
sc <- spark_connect(master = "local", version = "2.1.0")
df <- data.frame(replicate(2473,sample(0:1,100,rep=TRUE)))
df_tbl <- copy_to(sc, df)
arbol <- df_tbl %>%
  ml_decision_tree(X2000 ~ . -X1-X2-X3, type = "classification")
```

```
Error: org.apache.spark.SparkException: Job aborted due to stage failure: Task 0 in stage 31.0 failed 1 times, most recent failure: Lost task 0.0 in stage 31.0 (TID 129, localhost, executor driver): java.util.concurrent.ExecutionException: java.lang.Exception: failed to compile: org.codehaus.janino.JaninoRuntimeException: Code of method "eval(Lorg/apache/spark/sql/catalyst/InternalRow;)Z" of class "org.apache.spark.sql.catalyst.expressions.GeneratedClass$SpecificPredicate" grows beyond 64 KB
```

However, this works as expected in `Spark 2.2`:

```r
sc <- spark_connect(master = "local", version = "2.2.0")
df <- data.frame(replicate(2473,sample(0:1,100,rep=TRUE)))
df_tbl <- copy_to(sc, df)
df_tbl %>%
  ml_decision_tree(X2000 ~ . -X1-X2-X3, type = "classification")
```

```
* No rows dropped by 'na.omit' call
$features
   [1] "X4"    "X5"    "X6"    "X7"    "X8"    "X9"    "X10"   "X11"   "X12"   "X13" ...
 [ reached getOption("max.print") -- omitted 1469 entries ]

$response
[1] "X2000"

$max.bins
[1] 32

$max.depth
[1] 5

$categorical.transformations
<environment: 0x1171aab88>

$data
<jobj[7516]>
  class org.apache.spark.sql.Dataset
  [X1: int, X2: int ... 2472 more fields]

$ml.options
$id.column
[1] "id26f1380e5d50"

$response.column
[1] "response26f137104bf0"

$features.column
[1] "features26f1ee995ce"

$model.transform
NULL

$only.model
[1] FALSE

$na.action
[1] "na.omit"

attr(,"class")
[1] "ml_options"

$model.parameters
$model.parameters$features
[1] "features26f1ee995ce"

$model.parameters$labels
NULL

$model.parameters$response
[1] "response26f137104bf0"

$model.parameters$id
[1] "id26f1380e5d50"

$model.parameters$model
[1] "org.apache.spark.ml.classification.DecisionTreeClassifier"


$.call
ml_decision_tree(., X2000 ~ . - X1 - X2 - X3, type = "classification")

$.model
<jobj[17437]>
  class org.apache.spark.ml.classification.DecisionTreeClassificationModel
  DecisionTreeClassificationModel (uid=dtc_0648ee6c094b) of depth 5 with 29 nodes

attr(,"class")
[1] "ml_model_decision_tree" "ml_model"  
```

Closing issue since this is Spark specific and already fixed in latest version of Spark. Let us know if you hit any other issues in a new issue, thanks!

**Closed by javierluraschi** 2017-08-24 18:06 UTC
Labels: spark limitation
