### ISSUE TITLE
mutate_all() not working with list(~.) instead of funs(.) 

### ISSUE THREAD

**Issue by filipwastberg** [rstudio/sparklyr#1999] opened 2019-05-02 15:37 UTC
The `funs` call in `dplyr`'s `mutate_all()` has been soft deprecated as of dplyr 0.8.0.

Instead of writing:

```
library(dplyr)
mtcars %>% 
  mutate_all(funs(. * 1000))
```

You should write:

```
mtcars %>% 
  mutate_all(list(~. * 1000))
```

This works fine in R but does not work in `sparklyr`:
``` r
library(sparklyr)
library(dplyr)

config <- spark_config()
config$`sparklyr.shell.driver-memory` <- "2G"
config$`sparklyr.shell.executor-memory` <- "2G"

sc <- spark_connect(master = "local", config = config, spark_version = "2.1.0")
#> Registered S3 method overwritten by 'openssl':
#>   method      from
#>   print.bytes Rcpp

mtcars_spark <- copy_to(sc, mtcars, "mtcars")

mtcars_spark %>% 
  mutate_all(list(~. * 1000))
#> Error in as.pairlist(list(...)): object 'mpg' not found
```

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

``` r
- Session info ---------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.6.0 (2019-04-26)
 os       Windows 7 x64 SP 1          
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  Swedish_Sweden.1252         
 ctype    Swedish_Sweden.1252         
 tz       Europe/Berlin               
 date     2019-05-02                  

- Packages -------------------------------------------------------------------------------------------------------------
 ! package     * version    date       lib source                            
   askpass       1.1        2019-01-13 [1] CRAN (R 3.5.3)                    
   assertthat    0.2.1      2019-03-21 [1] CRAN (R 3.5.3)                    
   backports     1.1.4      2019-04-10 [1] CRAN (R 3.6.0)                    
   base64enc     0.1-3      2015-07-28 [1] CRAN (R 3.5.0)                    
   callr         3.2.0      2019-03-15 [1] CRAN (R 3.6.0)                    
   cli           1.1.0      2019-03-19 [1] CRAN (R 3.5.3)                    
   clipr         0.6.0      2019-04-15 [1] CRAN (R 3.6.0)                    
   config        0.3        2018-03-27 [1] CRAN (R 3.5.2)                    
   crayon        1.3.4      2017-09-16 [1] CRAN (R 3.5.1)                    
   curl          3.3        2019-01-10 [1] CRAN (R 3.5.3)                    
   DBI           1.0.0      2018-05-02 [1] CRAN (R 3.5.1)                    
   dbplyr        1.4.0      2019-04-23 [1] CRAN (R 3.6.0)                    
   desc          1.2.0      2018-05-01 [1] CRAN (R 3.5.1)                    
   devtools      2.0.2      2019-04-08 [1] CRAN (R 3.6.0)                    
   digest        0.6.18     2018-10-10 [1] CRAN (R 3.5.1)                    
   dplyr       * 0.8.0.9014 2019-04-30 [1] Github (tidyverse/dplyr@b8281c3)  
   ellipsis      0.1.0      2019-02-19 [1] CRAN (R 3.5.2)                    
   evaluate      0.13       2019-02-12 [1] CRAN (R 3.5.2)                    
   fansi         0.4.0      2018-10-05 [1] CRAN (R 3.5.1)                    
   forge         0.2.0      2019-02-26 [1] CRAN (R 3.5.3)                    
   fs            1.2.7      2019-03-19 [1] CRAN (R 3.6.0)                    
   generics      0.0.2      2018-11-29 [1] CRAN (R 3.5.1)                    
   glue          1.3.1      2019-03-12 [1] CRAN (R 3.5.3)                    
   htmltools     0.3.6      2017-04-28 [1] CRAN (R 3.5.1)                    
   htmlwidgets   1.3        2018-09-30 [1] CRAN (R 3.5.1)                    
   httr          1.4.0      2018-12-11 [1] CRAN (R 3.5.2)                    
   jsonlite      1.6        2018-12-07 [1] CRAN (R 3.5.2)                    
   knitr         1.22       2019-03-08 [1] CRAN (R 3.5.3)                    
   magrittr      1.5        2014-11-22 [1] CRAN (R 3.5.1)                    
   memoise       1.1.0      2017-04-21 [1] CRAN (R 3.5.1)                    
   openssl       1.3        2019-03-22 [1] CRAN (R 3.6.0)                    
   packrat       0.5.0      2018-11-14 [1] CRAN (R 3.5.2)                    
   pillar        1.3.1      2018-12-15 [1] CRAN (R 3.5.2)                    
   pkgbuild      1.0.3      2019-03-20 [1] CRAN (R 3.6.0)                    
   pkgconfig     2.0.2      2018-08-16 [1] CRAN (R 3.5.1)                    
   pkgload       1.0.2      2018-10-29 [1] CRAN (R 3.5.1)                    
   prettyunits   1.0.2      2015-07-13 [1] CRAN (R 3.5.1)                    
   processx      3.3.0      2019-03-10 [1] CRAN (R 3.5.3)                    
   ps            1.3.0      2018-12-21 [1] CRAN (R 3.5.3)                    
   purrr         0.3.2      2019-03-15 [1] CRAN (R 3.6.0)                    
   r2d3          0.2.3      2018-12-18 [1] CRAN (R 3.5.2)                    
   R6            2.4.0      2019-02-14 [1] CRAN (R 3.5.2)                    
   rappdirs      0.3.1      2016-03-28 [1] CRAN (R 3.5.2)                    
   Rcpp          1.0.1      2019-03-17 [1] CRAN (R 3.5.3)                    
   remotes       2.0.4      2019-04-10 [1] CRAN (R 3.6.0)                    
   reprex        0.2.1.9000 2019-04-30 [1] Github (tidyverse/reprex@8030fcf) 
   rlang         0.3.4      2019-04-07 [1] CRAN (R 3.5.3)                    
   rmarkdown     1.12.6     2019-04-16 [1] Github (rstudio/rmarkdown@9923811)
   rprojroot     1.3-2      2018-01-03 [1] CRAN (R 3.5.1)                    
   rstudioapi    0.10       2019-03-19 [1] CRAN (R 3.6.0)                    
   sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 3.5.3)                    
 V sparklyr    * 1.0.0      2019-05-02 [1] Github (rstudio/sparklyr@84b5bd5) 
   tibble        2.1.1      2019-03-16 [1] CRAN (R 3.5.3)                    
   tidyselect    0.2.5      2018-10-11 [1] CRAN (R 3.5.1)                    
   usethis       1.5.0      2019-04-07 [1] CRAN (R 3.6.0)                    
   utf8          1.1.4      2018-05-24 [1] CRAN (R 3.5.1)                    
   whisker       0.3-2      2013-04-28 [1] CRAN (R 3.5.1)                    
   withr         2.1.2      2018-03-15 [1] CRAN (R 3.5.1)                    
   xfun          0.6        2019-04-02 [1] CRAN (R 3.5.3)                    
   yaml          2.2.0      2018-07-25 [1] CRAN (R 3.5.1)                    

[1] C:/Users/xfilwas/R/library
[2] C:/Program Files/R/R-3.6.0/library

 V -- Loaded and on-disk version mismatch.
```

<sup>Created on 2019-05-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by neilmdixit** [comment] 2019-05-15 19:34
I'm encountering the same issue. Is there an update for this?

**Comment by kevinykuo** [comment] 2019-06-02 07:38
Looks to be a regression in dplyr, see upstream issue linked above. For now you can get around this by installing a previous release of dplyr via `remotes::install_github("tidyverse/dplyr", ref = "v0.8.0.1")`.

**Comment by kevinykuo** [comment] 2019-06-02 07:40
Closing since this isn't a sparklyr issue but please follow along in https://github.com/tidyverse/dplyr/issues/4393.

**Closed by kevinykuo** 2019-06-02 07:40 UTC
Labels: dplyr
