### ISSUE TITLE
implement save / load for 'ml_model' objects

### ISSUE THREAD

**Issue by kevinushey** [rstudio/sparklyr#134] opened 2016-07-28 20:16 UTC
The tricky part in saving these is that we also need a bit of extra metadata to re-construct the R object wrapper housing the Spark model object. So, on save, we would likely need to write two files, e.g.

```
/path/to/model_fit.mldata
/path/to/model_fit.rdata
```

The `model_fit.mldata` object would be created by e.g. `invoke(model$.model, "save", "/path/to/model_fit.mldata")`; the `model_fit.rdata` object might be implemented by e.g. `saveRDS()` and then copying that file to the Spark filesystem.

Loading would then just re-construct the `ml_model` object by loading the two files and duct-taping them back together.

**Comment by ElianoMarques** [comment] 2016-07-28 20:29
But if you load it in scala or java would it still work? the main goal of the load/ save model from the spark folks is to separate the development from deployment of the model, i.e. if you do a model in any language you can then load the model (and also pipeline) in any other language. I'm sure you seen this deck (slide 13)  and video [https://spark-summit.org/2016/events/apache-spark-mllib-20-preview-data-science-and-production](https://spark-summit.org/2016/events/apache-spark-mllib-20-preview-data-science-and-production) and also this blog post [https://databricks.com/blog/2016/07/26/introducing-apache-spark-2-0.html?utm_campaign=digest&utm_medium=email&utm_source=app](https://databricks.com/blog/2016/07/26/introducing-apache-spark-2-0.html?utm_campaign=digest&utm_medium=email&utm_source=app). The later has the R code they have used which shows the workaround required via the SparkR package. Hope its helpfull.

**Comment by kevinushey** [comment] 2016-07-28 20:50
Yes, it would still work fine -- we're still just calling the Scala `save` / `load` APIs, so it's identical to what would be produced had you been just writing your modeling code in Scala.

**Comment by kevinushey** [comment] 2016-07-28 20:52
One hiccup is that `save` does not save the training summary for linear regression fits, so we might have to work around that. (Unfortunately that limits interoperability when going from language to language, but I can't imagine why one would want to save the results of a linear model fit _without_ the actual summary.)

**Comment by ElianoMarques** [comment] 2016-07-28 21:18
Makes total sense, perhaps this package "save" can keep that metadata? One thing that would be great to have as well is the second derivatives of the survival regression optimizer to calculate the model statistics similar to gmls. It might be easier for the folks from spark to do it, i would need to investigate if the optimizer returns that info by default, if it does we could bring it up nicely similar to survreg. When you're more interested in the model coefs and not really the prediction its hard to understand if the coefs are stable or not without further info.

**Comment by kevinushey** [comment] 2016-07-28 21:29
We can certainly eagerly evaluate + store summary metadata as part of the R `ml_model` object when appropriate; we just avoid this for objects that are potentially large (e.g. the residuals).

Are there other pieces in http://spark.apache.org/docs/latest/api/scala/#org.apache.spark.ml.regression.AFTSurvivalRegressionModel that we could be extracting when producing survival regression model fits?

**Comment by ElianoMarques** [comment] 2016-07-28 21:35
Don't think so. We might need to open a ticket in jira to get this into roadmap.

**Comment by ElianoMarques** [comment] 2016-07-29 09:53
Confirmed we need to create a new jira ticket. Check the last two comments here: https://issues.apache.org/jira/browse/SPARK-8518

**Comment by MarcinKosinski** [comment] 2016-08-16 11:26
+1

**Comment by javierluraschi** [comment] 2016-11-04 22:24
Closing this one since currently Spark is missing to provide second derivates, once implemented in Spark, lets open a new issue to implement this in `sparklyr`.

**Closed by javierluraschi** 2016-11-04 22:24 UTC
Labels: ml
