### ISSUE TITLE
spark_apply is very slow

### ISSUE THREAD

**Issue by yuying273** [rstudio/sparklyr#1526] opened 2018-05-29 04:21 UTC
---
I tried to use `group_by` and `spark_apply` on the Parquet file but the process is extremely slow. The input Parquet data is 128GB saved on HDFS. The grouping variable has $2^21$ unique values.  What I did is I apply logistic regression on each subset (each subset is the same size, 64kb) groupby the the grouping variable, collect the coefficients estimate from each logistic regression on the subset and return the average of the coefficients. Here is my code:

```r
library(sparklyr)
library(dplyr)
library(magrittr)

spark_version <- "2.2.0"
sc <- spark_connect(master = "yarn-client", version = spark_version)
    start_time <- Sys.time()
    ## spark configuration
    config <- spark_config()   # Create a config to tune memory
    config$spark.executor.instances <- 199
    config$spark.network.timeout <- "800s"
    config$spark.sql.shuffle.partitions="2000"
    config$spark.executor.memory <- "20G"
    config[["sparklyr.shell.driver-memory"]] <- "10G"
    config$spark.executor.cores <- 2
    # create the Spark context
    sc <- spark_connect(master = "yarn", app_name = "myjob",version = "2.2.0",config=config) # using custom configs
    ## data input and output
    data_tbl = spark_read_parquet(sc,"data_tbl","Data_input_path_in_Yarn")
    read_time = Sys.time()
    t1 = as.numeric(read_time) - as.numeric(start_time)
    ## take t1=1.6 minutes to read in data
    ## logistic regression and coefficients
    coeffs = spark_apply(
      data_tbl,
      function(e){matrix(glm(y~v0+v1+v2+v3+v4+v5+v6+v7+v8+v9+v10+v11+v12+v13+v14-1,family=binomial(),data=e)$coef,nrow=1)},
      group_by = "g"
    )%>%
      summarize_all(mean)
    ana_time = Sys.time()
    t2 = as.numeric(ana_time) - as.numeric(read_time)
    ## take t2 = 9 minutes to run spark_apply
    coeffs
# A tibble: 1 x 16
#        g       v0      v1       v2       v3      v4      v5        v6       v7
#   <dbl>    <dbl>   <dbl>    <dbl>    <dbl>   <dbl>   <dbl>     <dbl>    <dbl>
#1  1.05e6  5.19e-5 0.00261  3.70e-5  8.01e-5 2.79e-5 1.49e-4  -6.70e-6  6.30e-6
# ... with 7 more variables: v8 <dbl>, v9 <dbl>, v10 <dbl>, v11 <dbl>,
#   v12 <dbl>, v13 <dbl>, v14 <dbl>

    ana2_time = Sys.time()
    t3 = as.numeric(ana2_time) - as.numeric(ana_time)
    ## take t3 = 2.8 hours to print coeffs???? Just one row tibble
    spark_disconnect(sc)
```
I assign the output of `sparkly_apply` to an object called `coeffs`. This took me 9 minutes. Then I print this object and it took me 2.8 hours!! I don't understand why printing the result of `spark_apply` takes such a long time. And you can see I need to specify `config$spark.executor.memory <- "20G"`, otherwise I have memory error. Is it because the grouping variable has too many unique values? Is there a efficient way to summarize the average coefficients of whole subset? 

Thank you very much!

Sincerely,

Yuying

**Comment by harryprince** [comment] 2018-05-29 09:33
the same issue for me.

**Comment by dalloliogm** [comment] 2018-06-05 14:39
The computation may happens only when you print it because of lazy execution in spark. You can force computation using compute() or collect(). Could you restructure your code in order to use the spark mllib implementation of logistic regression? how many groups do you have? Is your data partitioned by group?

**Comment by javierluraschi** [comment] 2018-09-11 20:37
As mentioned, please try to use first the `ml_` functions provided in `sparklyr`, as in `ml_logistic_regression()`, not `spark_apply()` as a start.

As of performance, we are improving performance of `spark_apply()` with https://github.com/rstudio/sparklyr/issues/1457

Going to close this one since there are better ways to perform this and perf is tracked by different issue.

**Closed by javierluraschi** 2018-09-11 20:37 UTC
Labels: distributed r

**Comment by talegari** [comment] 2022-03-10 12:46
My general observation: `spark_apply` is not usable (takes crazy long time and sometime does not even finish) even with `packages = FALSE`.

From a user's perspective, for someone who prefers to use `sparklyr` over `SparkR` (on databricks): `spark_apply` is the only thing where I  endup writing `SparkR::gapply` code which breaks the flow of code.

IMHO, `sparklyr` should **prioritize** efficient distributed computing with R which is a cornerstone for spark. There are situations beyond `ml_` functions.

**Comment by richy1996** [comment] 2023-03-11 21:39
here's a function i've been hacking together which calculates implied volatility of options with spark_apply. takes about 12 seconds for 12k rows of data in local R, has taken 3 hours on two different runs now with spark_apply/sparklyr. any suggestions?
Not sure why i can't get the below to render correctly..


`
nope_calls %>% # head %>% 
  spark_apply( 
    # group_by = "grouper", # doesn't work in conjunction rowwise or alone 
    function(e){ 
      library(dplyr) # THIS IS NECESSARY 
      e %>% 
        rowwise() %>% 
        mutate(
          call_implied_mid = tryCatch( 
            {
              greeks::BS_Implied_Volatility(
              option_price = CloseMidPrice, # option price
              initial_price = close, # underlying price 
              exercise_price = Strike, # strike price 
              r = 0, # default
              time_to_maturity = tt, # time to expiry in years
              dividend_yield = 0, # default
              payoff = "call" # call/put

              )# greek function

            },# tryCatch curly brace

            error=function(cond){
              NA 
            },
            warning=function(cond){
              NA 
            }

          )# tryCatch parenthesis

        )# mutate parenthesis

      # e # THIS ISN'T NECESSARY WHEN DONE LIKE THIS
      # NEITHER IS e$col_name before each column 

    },# function curly brace w/in spark_apply
    columns=schema,
    packages=F
)# spark_apply parenthesis
`

**Comment by richy1996** [comment] 2023-03-15 06:05
what helped significantly for me is making sure arrow was being used. discussed here https://therinspark.com/distributed.html, specifically section 11.9.2 Apache Arrow, maybe helps someone else
