### ISSUE TITLE
spark_connect hangs

### ISSUE THREAD

**Issue by Nova-Boy** [rstudio/sparklyr#542] opened 2017-03-09 22:15 UTC
Hi.  We have a CDH 5.10, Spark 1.6 environment w/ Kerberos, SSL and HA.  We're seeing endless hangs (I've let it go for upwards of 30 mins) during spark_connect both through RStudio and the cmd line using sparklyr 0.5.3.

```
sc <- spark_connect(master="yarn-client",
					version = "1.6.0",
					spark_home = "/opt/cloudera/parcels/CDH/lib/spark",
					config = list(
					default = list(
                                  spark.yarn.keytab= "/tmp/xx.keytab",
                                  spark.yarn.principal= "xx@yyy.PRI",
                                  sparklyr.gateway.start.timeout = "10"
								  )
							)
						)
```
(hangs until ctrl-c)

I can confirm that launching spark-shell w/ the keytab works as expected..

```
[mtz@nydc-edg02 ~]$ spark-shell --principal xx@yyy.PRI --keytab /tmp/xx.keytab
17/03/09 16:54:24 INFO security.UserGroupInformation: Login successful for user xx@yyy.PRI using keytab file /tmp/xx.keytab
Welcome to....
```

spark-submit works as expected..

`[mtz@nydc-edg02 ~]$ spark-submit --class org.apache.spark.examples.SparkPi --keytab /tmp/xx.keytab --principal xx@yyy.PRI spark-examples-1.6.0-cdh5.10.0-hadoop2.6.0-cdh5.10.0.jar 5`

Any thoughts on next steps here? Thanks!

**Comment by javierluraschi** [comment] 2017-03-09 22:44
@Nova-Boy Could you share the contents of `log4j.spark.log*` or any other relevant logs? Is this a regression or first time trying `sparklyr` in this cluster?

Also, I would rather try the following config to pass principal and keytab as parameters:

```
sc <- spark_connect(master="yarn-client",
					version = "1.6.0",
					spark_home = "/opt/cloudera/parcels/CDH/lib/spark",
					config = list(
					default = list(
                                            sparklyr.shell.keytab= "/tmp/xx.keytab",
                                            sparklyr.shell.principal= "xx@yyy.PRI",
                                            sparklyr.gateway.start.timeout = "10"
					)))
```

**Comment by Nova-Boy** [comment] 2017-03-10 03:52
@javierluraschi 

Thanks for the quick response!

Running the following from R shell..

```
library(sparklyr)								  
library(dplyr) 

sc <- spark_connect(
  master="yarn-client",
  version = "1.6.0",
  spark_home = "/opt/cloudera/parcels/CDH/lib/spark",
  config = list(
  default = list(
    sparklyr.shell.keytab= "/tmp/xx.keytab",
    sparklyr.shell.principal= "xx@yyy.PRI",
    sparklyr.gateway.start.timeout = "10"
)))

```

still causes a hang.  Prior to locating the driver logs in /tmp, I did try the exact same commands, but under my kinit'd AD account rather than my local (mtz) account, and it worked.  The problem is clearly auth, and the logs do confirm it.  Trying as local user w/ keytab again, I see...

```
17/03/09 22:43:08 INFO sparklyr: Session (6393) starting
17/03/09 22:43:08 INFO sparklyr: Registering session (6393) into gateway port (8880)
17/03/09 22:43:08 INFO sparklyr: Waiting for registration of (6393) into gateway port (8880)
17/03/09 22:43:08 INFO sparklyr: Finished registration of session (6393) into gateway port (8880) with status (0)
17/03/09 22:43:09 INFO sparklyr: Gateway received command identifier (0)
17/03/09 22:43:09 INFO sparklyr: Gateway found current session (6393)
17/03/09 22:43:09 INFO sparklyr: Gateway created backend for session (6393)
17/03/09 22:43:09 INFO sparklyr: Gateway waiting for r process to end in session (6393)
17/03/09 22:43:10 INFO spark.SparkContext: Running Spark version 1.6.0
17/03/09 22:43:11 INFO spark.SecurityManager: Changing view acls to: mtz
17/03/09 22:43:11 INFO spark.SecurityManager: Changing modify acls to: mtz
17/03/09 22:43:11 INFO spark.SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: Set(mtz); users with modify permissions: Set(mtz)
17/03/09 22:43:11 INFO util.Utils: Successfully started service 'sparkDriver' on port 34051.
17/03/09 22:43:11 INFO slf4j.Slf4jLogger: Slf4jLogger started
17/03/09 22:43:11 INFO Remoting: Starting remoting
17/03/09 22:43:11 INFO Remoting: Remoting started; listening on addresses :[akka.tcp://sparkDriverActorSystem@192.168.101.232:33577]
17/03/09 22:43:11 INFO Remoting: Remoting now listens on addresses: [akka.tcp://sparkDriverActorSystem@192.168.101.232:33577]
17/03/09 22:43:11 INFO util.Utils: Successfully started service 'sparkDriverActorSystem' on port 33577.
17/03/09 22:43:12 INFO spark.SparkEnv: Registering MapOutputTracker
17/03/09 22:43:12 INFO spark.SparkEnv: Registering BlockManagerMaster
17/03/09 22:43:12 INFO storage.DiskBlockManager: Created local directory at /tmp/blockmgr-48016859-fd16-4b18-8aed-4a51dc74b9db
17/03/09 22:43:12 INFO storage.MemoryStore: MemoryStore started with capacity 1060.0 MB
17/03/09 22:43:12 INFO spark.SparkEnv: Registering OutputCommitCoordinator
17/03/09 22:43:12 WARN util.Utils: Service 'SparkUI' could not bind on port 4040. Attempting port 4041.
17/03/09 22:43:12 INFO util.Utils: Successfully started service 'SparkUI' on port 4041.
17/03/09 22:43:12 INFO ui.SparkUI: Started SparkUI at http://192.168.101.232:4041
17/03/09 22:43:12 INFO spark.SparkContext: Added JAR file:/home/mtz/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/sparklyr-1.6-2.10.jar at spark://192.168.101.232:34051/jars/sparklyr-1.6-2.10.jar with timestamp 1489117392545
17/03/09 22:43:12 WARN security.UserGroupInformation: PriviledgedActionException as:mtz (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/03/09 22:43:12 WARN ipc.Client: Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
17/03/09 22:43:12 WARN security.UserGroupInformation: PriviledgedActionException as:mtz (auth:KERBEROS) cause:java.io.IOException: javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]

```

It doesn't even appear to be attempting the use of the keytab.

**Comment by Nova-Boy** [comment] 2017-03-10 04:00
Sorry...  re: regression, this is a new issue.  Just started working with sparklyr this morning.  :)

**Comment by Nova-Boy** [comment] 2017-03-10 04:56
Yeah, it's definitely not picking up the arguments...

```
config_sc <- list(config = config, master = master)
  message ('config_sc=', config_sc)
  shell_args <- connection_config(config_sc, "sparklyr.shell.")
  message ('shell_args= ', shell_args)
```

yields...

```
config_sc=list(default = list(sparklyr.shell.keytab = "/tmp/xx.keytab", sparklyr.shell.principal = "xx@yyy.PRI", sparklyr.gateway.start.timeout = "10"))yarn-client
shell_args=

```

I'm not much of an R dev, and my eyes are getting bleary, so this is about as far as I can go tonight.  Thanks.  :)

**Comment by Nova-Boy** [comment] 2017-03-10 05:08
connection_config processes the outermost config list, not config$default.  If I move the parameters out of default and into config, it picks up the arguments and works.

ie,

```

sc <- spark_connect(
  master="yarn-client",
  version = "1.6.0",
  spark_home = "/opt/cloudera/parcels/CDH/lib/spark",
  config = list(
    sparklyr.shell.keytab= "/tmp/xx.keytab",
    sparklyr.shell.principal= "xx@yyy.PRI",
    sparklyr.gateway.start.timeout = "10"
))	
```

Well, ALMOST works.. :)

```
Error in force(code) :
  Failed while connecting to sparklyr to port (8880) for sessionid (9569): non-numeric argument to binary operator
    Path: /opt/cloudera/parcels/CDH-5.10.0-1.cdh5.10.0.p0.41/lib/spark/bin/spark-submit
    Parameters: --keytab, /tmp/xx.keytab, --principal, xx@yyy.PRI, --class, sparklyr.Backend, '/home/mtz/R/x86_64-redhat-linux-gnu-library/3.3/sparklyr/java/sparklyr-1.6-2.10.jar', 8880, 9569


```

**Comment by Nova-Boy** [comment] 2017-03-10 05:26
Bah.  I took out the timeout arg AND stopped using my hacked-up version, and everything is working! That last issue was probably something in the debug version I was using.

Thanks for the help!!

**Comment by javierluraschi** [comment] 2017-03-13 18:45
@Nova-Boy awesome, thanks for sharing this, will help others! Closing issue.

**Closed by javierluraschi** 2017-03-13 18:45 UTC

**Comment by joscani** [comment] 2018-09-10 20:59
I have a similar problem. I can start spark using spark shell with valid kerberos ticket but I get 
`WARN security.UserGroupInformation: PriviledgedActionException as:oyrdatos (auth:KERBEROS) cause:javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
`
using sparklyr
