### ISSUE TITLE
log calculation in mutate  method returns 1/log

### ISSUE THREAD

**Issue by yesh-yb** [rstudio/sparklyr#609] opened 2017-04-10 16:36 UTC
issue re-surfaced in a different form,
mutate(log(n)) - this works 
mutate(myvar=log(n)) - this returns 1/log()

it happens only for natural logarithms!!!
please find the below code

```
> tt = copy_to(sc, data.frame(n=c(1, 2, 10)), name='testx')
> tt %>% mutate(myvar=log(n))
Source:   query [3 x 2]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      n     myvar
  <dbl>     <dbl>
1     1       Inf
2     2 1.4426950
3    10 0.4342945
> tt %>% mutate(log(n))
Source:   query [3 x 2]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      n  `log(n)`
  <dbl>     <dbl>
1     1 0.0000000
2     2 0.6931472
3    10 2.3025851
> tt %>% mutate(log2(n))
Source:   query [3 x 2]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      n `log2(n)`
  <dbl>     <dbl>
1     1  0.000000
2     2  1.000000
3    10  3.321928
> tt %>% mutate(myvar=log2(n))
Source:   query [3 x 2]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      n    myvar
  <dbl>    <dbl>
1     1 0.000000
2     2 1.000000
3    10 3.321928
> tt %>% mutate(myvar=log10(n))
Source:   query [3 x 2]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      n   myvar
  <dbl>   <dbl>
1     1 0.00000
2     2 0.30103
3    10 1.00000
> tt %>% mutate(log10(n))
Source:   query [3 x 2]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

      n `log10(n)`
  <dbl>      <dbl>
1     1    0.00000
2     2    0.30103
3    10    1.00000
> utils::sessionInfo()
R version 3.3.2 (2016-10-31)
Platform: x86_64-redhat-linux-gnu (64-bit)
Running under: CentOS Linux 7 (Core)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.5.0    sparklyr_0.5.3

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.9     digest_0.6.12   withr_1.0.2     rprojroot_1.2   assertthat_0.1  R6_2.2.0        jsonlite_1.3    DBI_0.6         backports_1.0.5
[10] magrittr_1.5    httr_1.2.1      lazyeval_0.2.0  tools_3.3.2     readr_1.0.0     base64enc_0.1-3 tibble_1.2   ```

**Comment by kevinushey** [comment] 2017-04-10 17:40
I'm not able to reproduce this issue with the development versions of dplyr / sparklyr. Can you double check whether this is resolved there for you as well?

```
devtools::install_github("rstudio/sparklyr")
```

For reference, I see:

```
> library(dplyr)
> library(sparklyr)
> 
> sc <- spark_connect(master = "local", version = "2.1.0")
> 
> tt = copy_to(sc, data.frame(n = c(1, 2, 10)), name = 'testx')
> tt %>% mutate(myvar = log(n))
Source:     lazy query [?? x 2]
Database:   spark_connection

      n     myvar
  <dbl>     <dbl>
1     1 0.0000000
2     2 0.6931472
3    10 2.3025851
```

**Comment by yesh-yb** [comment] 2017-04-20 15:59
apologies for the delayed response
issue still persists,
i am using rstudio server.

**Comment by JohnMount** [comment] 2017-04-30 17:29
I have run into a lot of log issues with Spark 1.6.2 and sparklyr 0.5.3 (going to try 0.5.4 next).  In particular natural log of 1 was some infinity or NaN and for 2,3,4,5 the value went down.  Switching to log10 moved away from this behavior.  The issue is on production systems we can choose our version of Sparklyr, but not always choose the version of Spark (as that is property of the cluster).

**Comment by javierluraschi** [comment] 2017-06-21 21:38
Tried to reproduce with Spark 1.5.2, Spark 1.6.2 and Spark 2.10, all against `dplyr` and `sparklyr` from CRAN. So far so good, closing.

**Closed by javierluraschi** 2017-06-21 21:38 UTC
Labels: dplyr
