### ISSUE TITLE
Odd Error: !is.null(statementReponse$output) is not TRUE

### ISSUE THREAD

**Issue by Deom23** [rstudio/sparklyr#1266] opened 2018-01-23 16:58 UTC
Ive been playing with a dataset in Spark using sparklyr and a Livy connection, but running into an issue when trying to build a predictive model. 

I got the data loaded just fine, was able to create some new variables and then trying to build a predictive model I get the following error: !is.null(statementReponse$output) is not TRUE

Here is the code I was trying to run at the time. 
#Build a model
gbm <- ml_gradient_boosted_trees(training,response = "target2",features = prediction_vars)

What does this error mean and how can I resolve it?

**Comment by bradleyhd** [comment] 2018-08-02 18:35
I just ran into this, by doing roughly the following:
```
install.packages("sparklyr")
library(sparklyr)
spark_install(version = "2.1.0")
options(sparklyr.verbose = TRUE)

sc <- spark_connect(master = "http://<private-ip>:8998", method = "livy")

library("dplyr")
copy_to(sc, iris)
```
which gave `Error: !is.null(statementReponse$output) is not TRUE`. I tried a second time and everything worked just fine ¯\_(ツ)_/¯

**Comment by kevinykuo** [comment] 2018-08-02 18:45
Looks like you might consider tweaking `livy.session.command.timeout` or `livy.session.command.interval`. See https://github.com/rstudio/sparklyr/pull/1541 and https://github.com/rstudio/sparklyr/issues/1538.

**Comment by ciasom** [comment] 2018-08-10 11:17
See https://issues.cloudera.org/browse/LIVY-202.  I'm not sure if sparkly can retry if statement state is available but output is NULL

**Comment by ciasom** [comment] 2018-08-27 07:02
As per my testing, this issue can be fixed by retrying in livy_post_statment when statement state is available but output is NULL, which means this situation can be treated the same as state = 'running' or 'waiting'.

**Comment by lgongmsft** [comment] 2019-05-25 15:04
Any update on this issue?  I am still running into it with sparklyr Version: 1.0.1.  Thanks!

**Comment by lgongmsft** [comment] 2019-05-28 16:48
@kevinykuo, any suggestion on how to tweak livy.session.command.timeout or livy.session.command.interval to make it always work?  The error seems random and not always reproducible.  Is it enough to just implement what @ciasom suggested (https://github.com/rstudio/sparklyr/issues/1266#issuecomment-416133981)?  Thanks!

**Comment by lgongmsft** [comment] 2019-05-31 04:50
In the case of statement output is null when state is "available", sparklyr fails the following assertion:

https://github.com/rstudio/sparklyr/blob/7479a60b223f213bf9d4ba416ef235b3c8b93102/R/livy_connection.R#L425

however, sparkmagic instead just returns an empty string:

https://github.com/jupyter-incubator/sparkmagic/blob/b9413e590d565390c517b016ba7bc436655f9a79/sparkmagic/sparkmagic/livyclientlib/command.py#L61

should it be done the same way in sparklyr or is it better to wait until the output is indeed available?

**Closed** 2019-06-02 18:26 UTC
Labels: livy, ml
