### ISSUE TITLE
Row binding large Spark DataFrames leads to a crash error.

### ISSUE THREAD

**Issue by wilvancleve** [rstudio/sparklyr#227] opened 2016-09-24 14:34 UTC
Howdy, all. 

I've got 8 approximately 20 GB parquet files which I sequentially load, filter down to about 150MB of data, and then want to combine into a single parquet file. The tables have identical structures.

I'm running a recently updated build of sparklyr from devtools on a 4 core macbook with 8GB of RAM.

In SparkR, this is no problem: I use SparkR::union and can easily bind them, and while the operation takes awhile, it's never been an issue.

In sparklyr, the write operation to the single new parquet file fails with the following error:

```
Error: org.apache.spark.SparkException: Job aborted.
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelationCommand.scala:149)
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1.apply(InsertIntoHadoopFsRelationCommand.scala:115)
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1.apply(InsertIntoHadoopFsRelationCommand.scala:115)
    at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
    at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:115)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:60)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:58)
    at org.apache.spark.sql.execution.command.ExecutedCommandExec.doExe
```

RStudio often (but doesn't always) crashes as well.

**Comment by kevinushey** [comment] 2016-09-26 17:55
Right now, RStudio doesn't handle aborted Spark jobs very well -- effectively, the connection can get into an inconsistent state, which basically causes 'weirdness' when RStudio pings the `Spark` instance in the background.

We do plan to improve the resilience of the backend, so hopefully issues like that will be resolved soon.

That said, I'm surprised you're seeing an issue in `sparklyr` but not `SparkR` here -- we're both calling the same DataFrame method (although we call `unionAll` rather than `union`).

Does the operation complete successfully if you try computing the union 'by hand', with e.g.

```
# suppose 'x', 'y' are 'tbl_spark's
sx <- spark_dataframe(x)
sy <- spark_dataframe(y)
su <- invoke(sx, "union", sy)
tbl <- sdf_register(su, "joined")
```

?

**Comment by wilvancleve** [comment] 2016-09-27 20:16
Nope, that one fails too, at Task 1701 of 1705.

```
Error: org.apache.spark.SparkException: Job aborted.
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1.apply$mcV$sp(InsertIntoHadoopFsRelationCommand.scala:149)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1.apply(InsertIntoHadoopFsRelationCommand.scala:115)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand$$anonfun$run$1.apply(InsertIntoHadoopFsRelationCommand.scala:115)
	at org.apache.spark.sql.execution.SQLExecution$.withNewExecutionId(SQLExecution.scala:57)
	at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelationCommand.run(InsertIntoHadoopFsRelationCommand.scala:115)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult$lzycompute(commands.scala:60)
	at org.apache.spark.sql.execution.command.ExecutedCommandExec.sideEffectResult(commands.scala:58)
	at `org.apache.spark.sql.execution.command.ExecutedCommandExec.doExe`
```

My guess is it's a RAM issue? Dunno what SparkR is doing to make the call more memory efficient... Here's the basics of the successful SparkR call

```
for (YEAR in YEARS) {
  name = paste(datapath,"prefix",YEAR,".parquet",sep="")
  df <- read.df(name, "parquet")
  df <- join(df, ton, (join criteria are here), "inner")
  df <- select(df, c("COL1","COL2","A BUNCH MORE COLS HERE"))
  if (YEAR == YEARS[1]) {
    all_outpt <- df
  } else {
    all_outpt <- SparkR::union(all_outpt, df)
  }
  all_outpt <- distinct(all_outpt)
}
```

**Comment by kevinushey** [comment] 2016-09-27 21:13
That's strange :/ I am guessing it must be a RAM issue as well, but I do not know why it would succeed in `SparkR` but not in `sparklyr`. We'll see if we can learn a bit more about what's going on; thanks!

**Comment by fereshtehRS** [comment] 2016-09-27 21:34
@wilvancleve Can you check the settings/environment when you run with `sparklyr` and compare it with when you run `sparkR`? You can use the Spark Web UI, and go to Environment tab for each job. If the memory settings for the 2 jobs are different, that could explain why `sparkR` is successful for the same operation (is it the exact same operation you run in the 2 cases?).

**Comment by wilvancleve** [comment] 2016-09-28 11:21
Turns out they _were_ slightly different, but they're now identical and I still get the same error. 

```
SparkR

Name	Value
spark.app.id	local-1475057342280
spark.app.name	SparkR
spark.debug.maxToStringFields	150
spark.driver.extraJavaOptions	-XX:+UseG1GC
spark.driver.host	192.168.2.109
spark.driver.memory	4g
spark.driver.port	52769
spark.executor.id	driver
spark.executorEnv.LD_LIBRARY_PATH	$LD_LIBRARY_PATH:
spark.home	/Users/wil/Library/Caches/spark/spark-2.0.0-bin-hadoop2.7
spark.kryoserializer.buffer.max	500MB
spark.master	local[*]
spark.scheduler.mode	FIFO
spark.serializer	org.apache.spark.serializer.KryoSerializer
spark.submit.deployMode


sparklyr

Name	Value
spark.app.id	local-1475058788192
spark.app.name	sparklyr
spark.debug.maxToStringFields	150
spark.driver.extraJavaOptions	-XX:+UseG1GC
spark.driver.host	127.0.0.1
spark.driver.memory	4g
spark.driver.port	56957
spark.executor.id	driver
spark.home	/Applications/spark-2.0.0-bin-hadoop2.7
spark.jars	file:/Users/wil/.ivy2/jars/com.databricks_spark-csv_2.11-1.3.0.jar,file:/Users/wil/.ivy2/jars/org.apache.commons_commons-csv-1.1.jar,file:/Users/wil/.ivy2/jars/com.univocity_univocity-parsers-1.5.1.jar,file:/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/java/sparklyr-2.0-2.11.jar
spark.kryoserializer.buffer.max	500MB
spark.master	local[*]
spark.scheduler.mode	FIFO
spark.serializer	org.apache.spark.serializer.KryoSerializer
spark.submit.deployMode	client
```

**Comment by javierluraschi** [comment] 2017-08-17 18:21
@wilvancleve we would need the original R code that was triggering this issue to make progress here.

My guess is that running this in `sparklyr` would fail:

```
p1 <- spark_read_parquet()
p2 <- spark_read_parquet()

p1 %>% union_all(p2)
```

since the `dplyr` union is being materialized while in `sparkR` the `all_outpt <- SparkR::union(all_outpt, df)` won't materialize it; however, this would be the same with `dplyr` if we run instead:

```
p1 <- spark_read_parquet()
p2 <- spark_read_parquet()

u1 <- p1 %>% union_all(p2)
```

Please open a new issue if you can still have a reproducible example around, @wilvancleve, otherwise, closing this one.

**Closed by javierluraschi** 2017-08-17 18:21 UTC
Labels: sdf
