### ISSUE TITLE
APPCRASH error for rsession.exe app

### ISSUE THREAD

**Issue by dsblr** [rstudio/sparklyr#564] opened 2017-03-19 22:28 UTC
Hello Sparklyr team,
please help me with the following error solution. 
Using sparklyr I am training Random Forest model and there was no error.
I have to build 20 models by changing to 20 different targets,
But while implementing that inside for loop I am getting APPCRASH error for rsession.exe and fault module name is ntdll.dll.
Please share some of your experience to solve the error.

Error:
Faulting application name: rsession.exe, version: 0.99.902.0, time stamp: 0x00000000
Faulting module name: ntdll.dll, version: 6.3.9600.18438, time stamp: 0x57ae642e
Exception code: 0xc0000005
Fault offset: 0x0000000000054a71
Faulting process id: 0xcc4
Faulting application start time: 0x01d29e9e8cac256d
Faulting application path: D:\Program Files\RStudio\bin\x64\rsession.exe
Faulting module path: C:\Windows\SYSTEM32\ntdll.dll
Report Id: ************************************
Faulting package full name: 
Faulting package-relative application ID:

**Comment by javierluraschi** [comment] 2017-03-21 17:38
@dsblr Could you share the code being used to train this model?

**Comment by dsblr** [comment] 2017-03-25 01:58
@javierluraschi Thanks for your response. Its working fine now after I used gc() inside the function. 
It was seems to be an memory exception error.

**Comment by javierluraschi** [comment] 2017-03-28 23:35
@dsblr You could also try using `Sys.sleep(2)` to help clean up resources after closing the connection.

**Comment by dsblr** [comment] 2017-05-10 23:32
@javierluraschi Thanks for your input.
 Sys.sleep(2) also not helpful to resolve the issue. This is not the memory exception issue, neither R/Rstudio issue.  
The reason for the error I observed, is due to spark_context, same spark_context I can't use to build all the model using for loop. The work around is that each time before every model build, I need to create a new spark context, and save the model. But since I am using Random Forest model on spark 1.6.0 version I cannot save the model https://github.com/rstudio/sparklyr/issues/449
I will upgrade the spark to 2.0 and check the same.

**Comment by javierluraschi** [comment] 2017-09-06 18:06
The appcrash was probably the `SIGPIPE` investigated/fixed with https://github.com/rstudio/sparklyr/issues/919, @dsblr try with the latest version of `sparklyr` by running `devtools::install_github("rstudio/sparklyr")` and reopen a new issue if the issue is still present for you, thank you!

**Closed by javierluraschi** 2017-09-06 18:06 UTC
Labels: desktop
