### ISSUE TITLE
Incorrect calculation for natural logarithms

### ISSUE THREAD

**Issue by hiltonmbr** [rstudio/sparklyr#646] opened 2017-04-29 12:19 UTC
When I use spark datasource, mutate procedure returns 1/log(x) instead of log(x) for natural logarithms!

For instance:

`df = copy_to(sc, data.frame(x=c(1:10)), name='example') `
`df %>% mutate(logx = log(x), logx10 = log10(x))`

`Source:   query [10 x 3]`
`Database: spark connection master=local[*] app=sparklyr local=TRUE`

`       x      logx    logx10`
`   <int>     <dbl>     <dbl>`
`1      1       Inf 0.0000000`
`2      2 1.4426950 0.3010300`
`3      3 0.9102392 0.4771213`
`4      4 0.7213475 0.6020600`
`5      5 0.6213349 0.6989700`
`6      6 0.5581106 0.7781513`
`7      7 0.5138983 0.8450980`
`8      8 0.4808983 0.9030900`
`9      9 0.4551196 0.9542425`
`10    10 0.4342945 1.0000000`

Any thoughts?

**Comment by JohnMount** [comment] 2017-04-30 17:32
I am seeing the same problem, and there is another issue open on it: https://github.com/rstudio/sparklyr/issues/35 .

**Comment by kevinushey** [comment] 2017-05-01 18:09
I'm not able to reproduce this issue when running `sparklyr` against the development version of `dplyr`.

**Comment by javierluraschi** [comment] 2017-05-10 09:15
@hiltonmbr can you share `sessionInfo()`?

Would be worth for us to track back what fixed this and share the details here.

**Comment by javierluraschi** [comment] 2017-06-21 21:38
Spent some time looking at `dplyr` and `sparklyr` changes, can't find the change that fixed this. Tried to reproduce with Spark 1.5.2, Spark 1.6.2 and Spark 2.10, all against `dplyr` and `sparklyr` from CRAN. So far so good, closing.

**Closed by javierluraschi** 2017-06-21 21:38 UTC
Labels: dplyr

**Comment by javierluraschi** [comment] 2017-06-21 21:45
It could be possible that a UDF was defined somewhere (not `sparklyr`) that would change this behavior.

@hiltonmbr, if you could share:

```r
df %>% mutate(logx = log(x), logx10 = log10(x)) %>% dbplyr::render_sql()
```

that should give us at least some idea of what could be causing this, Spark version, `sparklyr` version and `dplyr` version would help us troubleshoot this further.

**Comment by kevinushey** [comment] 2017-06-21 22:37
My guess is that the issue here was related to the following `dplyr` issue: https://github.com/tidyverse/dplyr/issues/2288
