### ISSUE TITLE
union and union_all appear to ignore column names on sparklyr

### ISSUE THREAD

**Issue by JohnMount** [rstudio/sparklyr#507] opened 2017-02-20 21:33 UTC
### Union order issue

spark and local data fames seem to have different union and union_all semantics (spark appears to use column indexes, and local seems to use column names).  Please see below for  a short example (and long documentation of environment).  

``` r
library('dplyr')
 #  
 #  Attaching package: 'dplyr'
 #  The following objects are masked from 'package:stats':
 #  
 #      filter, lag
 #  The following objects are masked from 'package:base':
 #  
 #      intersect, setdiff, setequal, union
library('sparklyr')
R.Version()$version.string
 #  [1] "R version 3.3.2 (2016-10-31)"
packageVersion('dplyr')
 #  [1] '0.5.0'
packageVersion('sparklyr')
 #  [1] '0.5.2'
my_db <- sparklyr::spark_connect(version='2.0.0', master = "local")
class(my_db)
 #  [1] "spark_connection"       "spark_shell_connection" "DBIConnection"
my_db$spark_home
 #  [1] "/Users/johnmount/Library/Caches/spark/spark-2.0.0-bin-hadoop2.7"
print(my_db)
 #  $master
 #  [1] "local[4]"
 #  
 #  $method
 #  [1] "shell"
 #  
 #  $app_name
 #  [1] "sparklyr"
 #  
 #  $config
 #  $config$sparklyr.cores.local
 #  [1] 4
 #  
 #  $config$spark.sql.shuffle.partitions.local
 #  [1] 4
 #  
 #  $config$spark.env.SPARK_LOCAL_IP.local
 #  [1] "127.0.0.1"
 #  
 #  $config$sparklyr.csv.embedded
 #  [1] "^1.*"
 #  
 #  $config$`sparklyr.shell.driver-class-path`
 #  [1] ""
 #  
 #  attr(,"config")
 #  [1] "default"
 #  attr(,"file")
 #  [1] "/Library/Frameworks/R.framework/Versions/3.3/Resources/library/sparklyr/conf/config-template.yml"
 #  
 #  $spark_home
 #  [1] "/Users/johnmount/Library/Caches/spark/spark-2.0.0-bin-hadoop2.7"
 #  
 #  $backend
 #          description               class                mode                text              opened 
 #  "->localhost:53247"          "sockconn"                "wb"            "binary"            "opened" 
 #             can read           can write 
 #                "yes"               "yes" 
 #  
 #  $monitor
 #         description              class               mode               text             opened 
 #  "->localhost:8880"         "sockconn"               "rb"           "binary"           "opened" 
 #            can read          can write 
 #               "yes"              "yes" 
 #  
 #  $output_file
 #  [1] "/var/folders/7q/h_jp2vj131g5799gfnpzhdp80000gn/T//Rtmpz5ZYCx/file126507d7ca72e_spark.log"
 #  
 #  $spark_context
 #  <jobj[5]>
 #    class org.apache.spark.SparkContext
 #    org.apache.spark.SparkContext@8dbf495
 #  
 #  $java_context
 #  <jobj[6]>
 #    class org.apache.spark.api.java.JavaSparkContext
 #    org.apache.spark.api.java.JavaSparkContext@a7cdca2
 #  
 #  $hive_context
 #  <jobj[9]>
 #    class org.apache.spark.sql.SparkSession
 #    org.apache.spark.sql.SparkSession@56ebcf45
 #  
 #  attr(,"class")
 #  [1] "spark_connection"       "spark_shell_connection" "DBIConnection"
```

-   Expected outcome: dplyr::union and dplyr::union\_all should match columns.
-   Observed outcome: matches columns on local data frames, matches positions on spark2.0.0.

``` r
d1 <- data.frame(year=2005:2010,
                 name='a',
                 stringsAsFactors = FALSE)
d2 <- data.frame(name='b',
                 year=2005:2010,
                 stringsAsFactors = FALSE)

# local frames: uses names on union
dplyr::union(d1, d2)
 #     year name
 #  1  2010    b
 #  2  2009    b
 #  3  2008    b
 #  4  2007    b
 #  5  2006    b
 #  6  2005    b
 #  7  2010    a
 #  8  2009    a
 #  9  2008    a
 #  10 2007    a
 #  11 2006    a
 #  12 2005    a
dplyr::union_all(d1, d2)
 #     year name
 #  1  2005    a
 #  2  2006    a
 #  3  2007    a
 #  4  2008    a
 #  5  2009    a
 #  6  2010    a
 #  7  2005    b
 #  8  2006    b
 #  9  2007    b
 #  10 2008    b
 #  11 2009    b
 #  12 2010    b


s1 <- copy_to(my_db, d1, 's1')
s2 <- copy_to(my_db, d2, 's2')

# remore frames: uses position, co-mingline different types
dplyr::union(s1,s2)
 #  Source:   query [12 x 2]
 #  Database: spark connection master=local[4] app=sparklyr local=TRUE
 #  
 #      year  name
 #     <chr> <chr>
 #  1   2007     a
 #  2      b  2008
 #  3      b  2010
 #  4   2006     a
 #  5   2008     a
 #  6      b  2006
 #  7   2009     a
 #  8   2010     a
 #  9   2005     a
 #  10     b  2005
 #  11     b  2007
 #  12     b  2009
dplyr::union_all(s1,s2)
 #  Source:   query [12 x 2]
 #  Database: spark connection master=local[4] app=sparklyr local=TRUE
 #  
 #      year  name
 #     <chr> <chr>
 #  1   2005     a
 #  2   2006     a
 #  3   2007     a
 #  4   2008     a
 #  5   2009     a
 #  6   2010     a
 #  7      b  2005
 #  8      b  2006
 #  9      b  2007
 #  10     b  2008
 #  11     b  2009
 #  12     b  2010
```

``` r
version
 #                 _                           
 #  platform       x86_64-apple-darwin13.4.0   
 #  arch           x86_64                      
 #  os             darwin13.4.0                
 #  system         x86_64, darwin13.4.0        
 #  status                                     
 #  major          3                           
 #  minor          3.2                         
 #  year           2016                        
 #  month          10                          
 #  day            31                          
 #  svn rev        71607                       
 #  language       R                           
 #  version.string R version 3.3.2 (2016-10-31)
 #  nickname       Sincere Pumpkin Patch
```

**Comment by kevinushey** [comment] 2017-02-21 04:00
Thanks for the reproducible example! It looks like the SQL generated here is as so:

```R
> query <- dplyr::union(s1, s2)
> rendered <- sql_render(query)
> as.character(rendered)
[1] "SELECT *\nFROM `s1`\nUNION\nSELECT *\nFROM `s2`"
```

It seems like the problem here occurs because the columns in `s1` and `s2` aren't in the same order, which makes me think this must be a bug in Spark (surely the column order shouldn't matter?)

**Comment by kevinykuo** [comment] 2017-02-21 04:13
http://stackoverflow.com/questions/32705056/what-is-going-wrong-with-unionall-of-spark-dataframe

R seems to treat this a bit differently than standard SQL, but perhaps we should tweak the behavior in sparklyr or at least throw a warning?

**Comment by kevinushey** [comment] 2017-02-21 04:33
Would it be acceptable to just transform `y` such that is has the same column order as `x`, or would this be surprising / unwarranted to users with more experience with SQL?

(How often do users perform a SQL `UNION` with the intention of union-ing columns based on order, rather than names? Is it common for users to manually re-order the tables before joining?)

**Comment by kevinykuo** [comment] 2017-02-21 04:52
Probably should leave this as is, if anything maybe include something in the dplyr code warning users about the discrepancy. See https://github.com/hadley/dplyr/issues/1045.

**Comment by JohnMount** [comment] 2017-02-21 06:03
Part of the issue is there does not appear to be a bind_rows for sparklyr- so one is forced to make due with union.  An R user is going to expect some adaption and R-like semantics through a "dplyr interface."

**Comment by kevinykuo** [comment] 2017-02-22 18:17
Right, I think this comes down to the lack of `bind_rows`, and we should be good when that's implemented, which isn't possible until https://github.com/hadley/dplyr/issues/2457 has been resolved.

**Comment by hadley** [comment] 2017-02-27 13:38
Given that you almost certainly want to match columns by names, I think that this is an issue with dplyr's implementation of `UNION` and `UNION ALL` (and probably `intersect()` and `setdiff()` too). Can someone please file an issue on dplyr with a minimal reprex created using `memdb_frame()`?

I see someone did mention that on the closed dplyr issue, but commenting on closed issues is an extremely bad way to get my attention.

@kevinushey I think you can close this issue since it's not a sparklyr problem

**Comment by kevinykuo** [comment] 2017-02-27 14:53
I think the issue comes down to not having `bind_rows()` in sparklyr. For consistency with SQL I wouldn't change the behavior of `union()` and `union_all()`. Perhaps we should close this and re-open https://github.com/rstudio/sparklyr/issues/505?

**Comment by hadley** [comment] 2017-02-27 15:07
I think the behaviour of `union()` and `union_all()` is currently extremely dangerous, and I don't think we need to be consistent with SQL here.  

There's currently no point in trying to build anything on top of `bind_rows()` because it doesn't do any dispatch.

**Comment by javierluraschi** [comment] 2017-05-10 07:27
Before closing this we need to file the bug with minimal repro that Hadley requested.

**Comment by javierluraschi** [comment] 2017-06-21 00:01
Was going to open a `dplyr` bug but seems to me this is already fixed. Closing.

```
> dplyr::union(s1,s2)
# Source:   lazy query [?? x 2]
# Database: spark_connection
    year  name
   <int> <chr>
 1  2010     a
 2  2005     b
 3  2007     b
 4  2006     a
 5  2005     a
 6  2009     a
 7  2006     b
 8  2008     b
 9  2010     b
10  2007     a
11  2008     a
12  2009     b
> dplyr::union_all(s1,s2)
# Source:   lazy query [?? x 2]
# Database: spark_connection
    year  name
   <int> <chr>
 1  2005     a
 2  2006     a
 3  2007     a
 4  2008     a
 5  2009     a
 6  2010     a
 7  2005     b
 8  2006     b
 9  2007     b
10  2008     b
11  2009     b
12  2010     b
```

**Closed** 2017-06-21 00:01 UTC
Labels: dplyr
