### ISSUE TITLE
select() doesn't work in sparklyr

### ISSUE THREAD

**Issue by BigZihao** [rstudio/sparklyr#485] opened 2017-02-13 08:14 UTC
Hi there, I am learning the example from tutorial (http://spark.rstudio.com/dplyr.html), but it give me error when I use select() in sparklyr:

sc <- spark_connect(master = "yarn-client",version = '2.0.0')
library(sparklyr)
> library(dplyr)
> library(nycflights13)
> library(ggplot2)
> flights <- copy_to(sc, flights, "flights")
> airlines <- copy_to(sc, airlines, "airlines")
> src_tbls(sc)
[1] "airlines" "flights"  "nypd"    
> select(flights, year:day, arr_delay, dep_delay)
Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘select’ for signature ‘"tbl_spark"’

Why will this happen?

**Comment by edgararuiz** [comment] 2017-02-13 13:44
Hi @BigZihao, I just tested this in a 'yarn-client' environment and it worked.  Could this be a package version issue?  

Can you share with me the results of running ``` sessionInfo() ``` in your machine?

**Comment by javierluraschi** [comment] 2017-02-13 17:21
@BigZihao typo? `select(flights, year:day, arr_delay, dep_delay)` notice `:` between `year` and `day`.

**Comment by BigZihao** [comment] 2017-02-14 18:24
Hi @edgararuiz , I am running on EMR on AWS, I create the cluster using the following aws cli:

aws emr create-cluster --applications Name=Hadoop Name=Spark Name=Hive Name=Pig Name=Tez Name=Ganglia \
--release-label emr-5.2.0 --name "EMR 5.2.0 RStudio + sparklyr" --service-role EMR_DefaultRole \
--instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m3.2xlarge \
InstanceGroupType=CORE,InstanceCount=5,InstanceType=m3.2xlarge --bootstrap-actions \
Path=s3://aws-bigdata-blog/artifacts/aws-blog-emr-rstudio-sparklyr/rstudio_sparklyr_emr5.sh,\
Args=["--rstudio","--sparkr","--rexamples","--plyrmr","--rhdfs","--sparklyr"],\
Name="Install RStudio" --ec2-attributes InstanceProfile=EMR_EC2_DefaultRole,KeyName=sparklyr \
--configurations '[{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true"}}]' \
--region us-east-1

I think this would contain all environment information

Then I login into R stuido on aws and run the the following code:

sc <- spark_connect(master = "yarn-client",version = '2.0.0')
library(sparklyr)
library(dplyr)
library(nycflights13)
library(ggplot2)
flights <- copy_to(sc, flights, "flights")
airlines <- copy_to(sc, airlines, "airlines")
src_tbls(sc)
[1] "airlines" "flights" "nypd"
select(flights, year:day, arr_delay, dep_delay)
Error in (function (classes, fdef, mtable) :
unable to find an inherited method for function ‘select’ for signature ‘"tbl_spark"’

It looks all the other functions in dpylr works fine(group_by, mutate), only select has Error 

Any idea?

**Comment by BigZihao** [comment] 2017-02-14 18:27
Hi @javierluraschi , this is not a typo, it means select column to "year" to column "day", and it is copy from the tutorial  http://spark.rstudio.com/dplyr.html

I am wondering what is the Error mean, why there's no inherited method for function ‘select’ for signature ‘"tbl_spark"’

**Comment by BigZihao** [comment] 2017-02-14 18:29
Hi @javierluraschi this is not typo, I believe it means select column "year" to column "day", and it is copy from the tutorial (http://spark.rstudio.com/dplyr.html)

I am wondering what is the Error mean, why there's no inherited method for function ‘select’ for signature ‘"tbl_spark"’ ?

**Comment by javierluraschi** [comment] 2017-02-14 20:03
@BigZihao Right! I totally forgot about the use of `:`, yes, that's no typo.

However, there is something missing in your steps, I just tried this over EMR successfully:

```
javierluraschi$ aws emr create-cluster --applications Name=Hadoop Name=Spark Name=Hive Name=Pig Name=Tez Name=Ganglia --release-label emr-5.2.0 --name "EMR 5.2.0 RStudio + sparklyr" --service-role EMR_DefaultRole --instance-groups InstanceGroupType=MASTER,InstanceCount=1,InstanceType=m3.2xlarge InstanceGroupType=CORE,InstanceCount=1,InstanceType=m3.2xlarge --bootstrap-actions Path=s3://aws-bigdata-blog/artifacts/aws-blog-emr-rstudio-sparklyr/rstudio_sparklyr_emr5.sh,Args=["--rstudio","--sparkr","--rexamples","--plyrmr","--rhdfs","--sparklyr"],Name="Install RStudio" --ec2-attributes InstanceProfile=EMR_EC2_DefaultRole,KeyName=sparklyr --configurations '[{"Classification":"spark","Properties":{"maximizeResourceAllocation":"true"}}]' --region us-east-1
```

```
R version 3.2.2 (2015-08-14) -- "Fire Safety"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> sc <- spark_connect(master = "yarn-client",version = '2.0.0')
Error: could not find function "spark_connect"
> library(sparklyr)
> sc <- spark_connect(master = "yarn-client",version = '2.0.0')
> flights <- copy_to(sc, flights, "flights")
Error in sdf_import(x, sc, name, memory, repartition, overwrite, ...) : 
  object 'flights' not found
> library(dplyr)

Attaching package: ‘dplyr’

The following objects are masked from ‘package:stats’:

    filter, lag

The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union

> library(nycflights13)
> library(ggplot2)
> flights <- copy_to(sc, flights, "flights")
> airlines <- copy_to(sc, airlines, "airlines")
> src_tbls(sc)
[1] "airlines" "flights" 
> select(flights, year:day, arr_delay, dep_delay)
Source:   query [3.368e+05 x 5]
Database: spark connection master=yarn-client app=sparklyr local=FALSE

    year month   day arr_delay dep_delay
   <int> <int> <int>     <dbl>     <dbl>
1   2013     1     1        11         2
2   2013     1     1        20         4
3   2013     1     1        33         2
4   2013     1     1       -18        -1
5   2013     1     1       -25        -6
6   2013     1     1        12        -4
7   2013     1     1        19        -5
8   2013     1     1       -14        -3
9   2013     1     1        -8        -3
10  2013     1     1         8        -2
# ... with 3.368e+05 more rows
```

Some thoughts, this error could happen if `flights` from `flights <- copy_to(sc, flights, "flights")` gets it's class modified. In general, I would recommend renaming the object, say as `flights_tbl <- copy_to(sc, flights, "flights")`; otherwise, you are overwriting the object from the `nycflights13`, which is OK, but if the `copy_to` operation fails, you could be trying to work against a data frame, not a Spark data frame since the overwrite never completed.

**Comment by niketdoshi** [comment] 2017-02-19 09:17
Select is behaving abnormally in my case. It's returning only one column no matter how many I select.

> R code

    library(doMC)
    library(dplyr)
    library(sparklyr)
    
    if(Sys.getenv("SPARK_HOME") == "")
    Sys.setenv(SPARK_HOME="~/Library/Caches/spark/spark-2.1.0-bin-hadoop2.7")

    # Spark configuration
    config <- spark_config()
    config$`sparklyr.shell.driver-memory` <- "8G"
    config$`sparklyr.shell.executor-memory` <- "8G"
    config$`spark.yarn.executor.memoryOverhead` <- "4G"

    sc <- spark_connect(master = "local", config = config, app_name = "test", version = "2.1.0")

    iris_sdf <- copy_to(sc, iris, "iris_spark")

> Output

    > select(iris_sdf, starts_with("Petal"))
    Source:   query [150 x 1]
    Database: spark connection master=local[8] app=test local=TRUE

    Petal_Length
          <dbl>
    1      1.4
    2      1.4
    3      1.3
    4      1.5
    5      1.4
    6      1.7
    7      1.4
    8      1.5
    9      1.4
    10     1.5
    # ... with 140 more rows

> Output

    > select(iris_sdf, -Sepal_Width)
    Source:   query [150 x 1]
    Database: spark connection master=local[8] app=test local=TRUE

    Sepal_Length
          <dbl>
    1      5.1
    2      4.9
    3      4.7
    4      4.6
    5      5.0
    6      5.4
    7       4.6
    8       5.0
    9       4.4
    10      4.9
    # ... with 140 more rows

> Session Info

    > sessionInfo()
    R version 3.3.2 (2016-10-31)
    Platform: x86_64-apple-darwin13.4.0 (64-bit)
    Running under: macOS Sierra 10.12.3

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] parallel  stats     graphics  grDevices utils     datasets  methods   base     

    other attached packages:
    [1] devtools_1.12.0     sparklyr_0.5.3-9002 dplyr_0.5.0.9000    doMC_1.3.4          iterators_1.0.8    
    [6] foreach_1.4.3 

It gives the same result when I use spark version 2.0.0.

Any idea what's going on here?

**Comment by BigZihao** [comment] 2017-02-22 14:36
Hi @javierluraschi ,

I closed my EMR, so I cannot trace back what I did getting those error. And I tried few times since you answered last time, they all give right answer as you do. I still don't know why I got the error back then but it works perfect fine now. 

Thank you so much, I will close the issue.

**Comment by javierluraschi** [comment] 2017-02-22 17:32
@niketdoshi could you retry with the latest build? We did have a regression a few days ago so perhaps you have an older build?

```
remove.packages("sparklyr")
devtools::install_github("rstudio/sparklyr")
```

@BigZihao I agree, feel free to close this one. If you have a chance, adding a couple more `dplyr` tests for the database name feature would help a lot: https://github.com/rstudio/sparklyr/blob/master/tests/testthat/test-dplyr.R

**Comment by niketdoshi** [comment] 2017-02-23 10:12
Hi @javierluraschi, thanks for the reply. 

I was trying it with the latest build of `sparklyr`. I think the problem was with the latest build of `dplyr`. When I reinstalled the CRAN version of dplyr, it worked fine.

Do you think it could be an issue?

**Closed** 2017-02-24 21:14 UTC

**Comment by AymericLechevranton** [comment] 2020-07-03 21:26
I just want to answer simply to the question of how to use the "select" function when you use "sparklyr" and you get this error:
-- Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘select’ for signature ‘"tbl_spark"’ --

You should simply add "dplyr" before "select" in order to work properly : 
dplyr::select()
